In [ ]:
#Business problem statement + Data Merging
1. Inpatient + Outpatient = final_patient
2. final_patient + train = fp_v1
3. fp_v1 + beneficiary data = final data

In [ ]:
# data merging
# EDA (Missing values, graphs, plots)
# Outlier treatments, Imputations
# Feature engineering
# Model Building
# Model Training 
# Model Evaluation

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [2]:
inpatient_data = pd.read_csv('Train_Inpatientdata.csv')
train = pd.read_csv('Train.csv')
ben_data = pd.read_csv('Train_Beneficiarydata.csv')

In [3]:
outpatient_data = pd.read_csv('Train_Outpatientdata.csv')

In [4]:
inpatient_data.describe()

,InscClaimAmtReimbursed,DeductibleAmtPaid,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
count,40474.000000,39575.0,23148.000000,5454.000000,965.000000,116.000000,9.000000,0.0
mean,10087.884074,1068.0,5894.611759,4103.738174,4226.355440,4070.172414,5269.444444,NaN
std,10303.099402,0.0,3049.304400,2028.182156,2282.761581,1994.409802,2780.071632,NaN
min,0.000000,1068.0,11.000000,42.000000,42.000000,42.000000,2724.000000,NaN
25%,4000.000000,1068.0,3848.000000,2724.000000,2724.000000,2758.750000,4139.000000,NaN
50%,7000.000000,1068.0,5369.000000,4019.000000,4019.000000,4019.000000,4139.000000,NaN
75%,12000.000000,1068.0,8666.250000,4439.000000,5185.000000,4439.000000,5185.000000,NaN
max,125000.000000,1068.0,9999.000000,9999.000000,9999.000000,9986.000000,9982.000000,NaN

In [5]:
inpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40474 entries, 0 to 40473
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BeneID                  40474 non-null  object
 1   ClaimID                 40474 non-null  object
 2   ClaimStartDt            40474 non-null  object
 3   ClaimEndDt              40474 non-null  object
 4   Provider                40474 non-null  object
 5   InscClaimAmtReimbursed  40474 non-null  int64
 6   AttendingPhysician      40362 non-null  object
 7   OperatingPhysician      23830 non-null  object
 8   OtherPhysician          4690 non-null   object
 9   AdmissionDt             40474 non-null  object
 10  ClmAdmitDiagnosisCode   40474 non-null  object
 11  DeductibleAmtPaid       39575 non-null  float64
 12  DischargeDt             40474 non-null  object
 13  DiagnosisGroupCode      40474 non-null  object
 14  ClmDiagnosisCode_1      40474 non-null  object
 15  ClmDiagnosisCode_2      40248 non-null  object
 16  ClmDiagnosisCode_3      39798 non-null  object
 17  ClmDiagnosisCode_4      38940 non-null  object
 18  ClmDiagnosisCode_5      37580 non-null  object
 19  ClmDiagnosisCode_6      35636 non-null  object
 20  ClmDiagnosisCode_7      33216 non-null  object
 21  ClmDiagnosisCode_8      30532 non-null  object
 22  ClmDiagnosisCode_9      26977 non-null  object
 23  ClmDiagnosisCode_10     3927 non-null   object
 24  ClmProcedureCode_1      23148 non-null  float64
 25  ClmProcedureCode_2      5454 non-null   float64
 26  ClmProcedureCode_3      965 non-null    float64
 27  ClmProcedureCode_4      116 non-null    float64
 28  ClmProcedureCode_5      9 non-null      float64
 29  ClmProcedureCode_6      0 non-null      float64
dtypes: float64(7), int64(1), object(22)
memory usage: 9.3+ MB

In [ ]:
40000, 
0 non-null in a column
no of null = no of rows - no of non null
          = 40000 - 0 = 40000

In [6]:
inpatient_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN

In [7]:
outpatient_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,10/11/2009,10/11/2009,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2/12/2009,2/12/2009,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,6/27/2009,6/27/2009,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,1/6/2009,1/6/2009,PRV56011,40,PHY334319,NaN,NaN,71988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,1/22/2009,1/22/2009,PRV56011,200,PHY403831,NaN,NaN,82382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947

In [8]:
outpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517737 entries, 0 to 517736
Data columns (total 27 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   BeneID                  517737 non-null  object
 1   ClaimID                 517737 non-null  object
 2   ClaimStartDt            517737 non-null  object
 3   ClaimEndDt              517737 non-null  object
 4   Provider                517737 non-null  object
 5   InscClaimAmtReimbursed  517737 non-null  int64
 6   AttendingPhysician      516341 non-null  object
 7   OperatingPhysician      90617 non-null   object
 8   OtherPhysician          195046 non-null  object
 9   ClmDiagnosisCode_1      507284 non-null  object
 10  ClmDiagnosisCode_2      322357 non-null  object
 11  ClmDiagnosisCode_3      203257 non-null  object
 12  ClmDiagnosisCode_4      125596 non-null  object
 13  ClmDiagnosisCode_5      74344 non-null   object
 14  ClmDiagnosisCode_6      48756 non-null   object
 15  ClmDiagnosisCode_7      32961 non-null   object
 16  ClmDiagnosisCode_8      22912 non-null   object
 17  ClmDiagnosisCode_9      14838 non-null   object
 18  ClmDiagnosisCode_10     1083 non-null    object
 19  ClmProcedureCode_1      162 non-null     float64
 20  ClmProcedureCode_2      36 non-null      float64
 21  ClmProcedureCode_3      4 non-null       float64
 22  ClmProcedureCode_4      2 non-null       float64
 23  ClmProcedureCode_5      0 non-null       float64
 24  ClmProcedureCode_6      0 non-null       float64
 25  DeductibleAmtPaid       517737 non-null  int64
 26  ClmAdmitDiagnosisCode   105425 non-null  object
dtypes: float64(6), int64(2), object(19)
memory usage: 106.7+ MB

In [9]:
train.head()

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No
3  PRV51005            Yes
4  PRV51007             No

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Provider        5410 non-null   object
 1   PotentialFraud  5410 non-null   object
dtypes: object(2)
memory usage: 84.7+ KB

In [11]:
ben_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138556 entries, 0 to 138555
Data columns (total 25 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   BeneID                           138556 non-null  object
 1   DOB                              138556 non-null  object
 2   DOD                              1421 non-null    object
 3   Gender                           138556 non-null  int64
 4   Race                             138556 non-null  int64
 5   RenalDiseaseIndicator            138556 non-null  object
 6   State                            138556 non-null  int64
 7   County                           138556 non-null  int64
 8   NoOfMonths_PartACov              138556 non-null  int64
 9   NoOfMonths_PartBCov              138556 non-null  int64
 10  ChronicCond_Alzheimer            138556 non-null  int64
 11  ChronicCond_Heartfailure         138556 non-null  int64
 12  ChronicCond_KidneyDisease        138556 non-null  int64
 13  ChronicCond_Cancer               138556 non-null  int64
 14  ChronicCond_ObstrPulmonary       138556 non-null  int64
 15  ChronicCond_Depression           138556 non-null  int64
 16  ChronicCond_Diabetes             138556 non-null  int64
 17  ChronicCond_IschemicHeart        138556 non-null  int64
 18  ChronicCond_Osteoporasis         138556 non-null  int64
 19  ChronicCond_rheumatoidarthritis  138556 non-null  int64
 20  ChronicCond_stroke               138556 non-null  int64
 21  IPAnnualReimbursementAmt         138556 non-null  int64
 22  IPAnnualDeductibleAmt            138556 non-null  int64
 23  OPAnnualReimbursementAmt         138556 non-null  int64
 24  OPAnnualDeductibleAmt            138556 non-null  int64
dtypes: int64(21), object(4)
memory usage: 26.4+ MB

In [12]:
ben_data.head()

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaN,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaN,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaN,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200

In [13]:
# final_patient_data = pd.merge(inpatient_data, outpatient_data, )

In [14]:
len(inpatient_data.columns.tolist())

30

In [15]:
len(outpatient_data.columns.tolist())

27

In [16]:
len([col_name for col_name in outpatient_data.columns.tolist() if col_name in inpatient_data.columns.tolist()])

27

In [17]:
final_patient = pd.merge(inpatient_data, outpatient_data, 
left_on = [col for col in outpatient_data.columns if col in inpatient_data.columns],
right_on = [col for col in outpatient_data.columns if col in inpatient_data.columns]
, how = 'outer') #inner join, outer join(NA)

In [18]:
outpatient_data.shape

(517737, 27)

In [19]:
inpatient_data.shape

(40474, 30)

In [20]:
final_patient.shape

(558211, 30)

In [21]:
pd.set_option("display.max_columns", None)

In [22]:
final_patient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,6186,1068.0,2009-09-02,750,6186,2948,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,29590,1068.0,2009-09-20,883,29623,30390,71690,34590,V1581,32723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,431,1068.0,2009-02-22,067,43491,2762,7843,32723,V1041,4254,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,78321,1068.0,2009-08-30,975,042,3051,34400,5856,42732,486,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN

In [23]:
final_patient['BeneID'].nunique()

138556

In [24]:
ben_data['BeneID'].nunique()

138556

In [25]:
ben_data.shape

(138556, 25)

In [26]:
final_ben = pd.merge(final_patient, ben_data, on = 'BeneID', how = 'inner')

In [27]:
final_ben.shape

(558211, 54)

In [28]:
final_ben.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,6186,1068.0,2009-09-02,750,6186,2948,56400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,29590,1068.0,2009-09-20,883,29623,30390,71690,34590,V1581,32723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,431,1068.0,2009-02-22,067,43491,2762,7843,32723,V1041,4254,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN,1914-03-01,NaN,2,2,0,1,360,12,12,2,1,1,2,2,1,1,2,2,1,1,5000,1068,250,320
4,BENE11011,CLM144521,1/18/2009,1/18/2009,PRV52314,50,PHY379398,NaN,NaN,NaN,78900,0.0,NaN,NaN,78969,78701,V5866,59389,2449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1914-03-01,NaN,2,2,0,1,360,12,12,2,1,1,2,2,1,1,2,2,1,1,5000,1068,250,320

In [29]:
train['Provider'].nunique()

5410

In [30]:
final_ben['Provider'].nunique()

5410

In [31]:
final_ben.shape

(558211, 54)

In [32]:
final_data = pd.merge(final_ben, train, on = 'Provider', how = 'outer')

In [33]:
final_data.shape

(558211, 55)

In [34]:
final_data.head().transpose()

,0,1,2,3,4
BeneID,BENE11001,BENE16973,BENE17521,BENE21718,BENE22934
ClaimID,CLM46614,CLM565430,CLM34721,CLM72336,CLM73394
ClaimStartDt,2009-04-12,9/6/2009,2009-01-20,2009-10-17,2009-10-25
ClaimEndDt,2009-04-18,9/6/2009,2009-02-01,2009-11-04,2009-10-29
Provider,PRV55912,PRV55912,PRV55912,PRV55912,PRV55912
InscClaimAmtReimbursed,26000,50,19000,17000,13000
AttendingPhysician,PHY390922,PHY365867,PHY349293,PHY334706,PHY390614
OperatingPhysician,NaN,PHY327147,PHY370861,PHY334706,PHY323689
OtherPhysician,NaN,NaN,PHY363291,NaN,PHY363291
AdmissionDt,2009-04-12,NaN,2009-01-20,2009-10-17,2009-10-25
ClmAdmitDiagnosisCode,7866,NaN,45340,V5789,71946
DeductibleAmtPaid,1068,0,1068,1068,1068
DischargeDt,2009-04-18,NaN,2009-02-01,2009-11-04,2009-10-29
DiagnosisGroupCode,201,NaN,987,941,506
ClmDiagnosisCode_1,1970,V7183,4240,V5789,71535
ClmDiagnosisCode_2,4019,53081,2639,4168,71960
ClmDiagnosisCode_3,5853,78959,2948,73313,4019
ClmDiagnosisCode_4,7843,4280,40390,7812,V1202
ClmDiagnosisCode_5,2768,E8788,45821,7993,4240
ClmDiagnosisCode_6,71590,78079,28489,78830,2449
ClmDiagnosisCode_7,2724,79902,5854,72273,2768
ClmDiagnosisCode_8,19889,25002,2753,43812,NaN
ClmDiagnosisCode_9,5849,71848,E9305,4019,NaN
ClmDiagnosisCode_10,NaN,NaN,NaN,NaN,NaN
ClmProcedureCode_1,NaN,NaN,7769,9338,8154
ClmProcedureCode_2,NaN,NaN,5849,NaN,NaN
ClmProcedureCode_3,NaN,NaN,NaN,NaN,NaN
ClmProcedureCode_4,NaN,NaN,NaN,NaN,NaN
ClmProcedureCode_5,NaN,NaN,NaN,NaN,NaN
ClmProcedureCode_6,NaN,NaN,NaN,NaN,NaN
DOB,1943-01-01,1932-05-01,1913-12-01,1922-10-01,1930-07-01
DOD,NaN,NaN,NaN,NaN,NaN
Gender,1,1,2,1,2
Race,1,1,1,1,1
RenalDiseaseIndicator,0,0,0,0,0
State,39,39,39,39,39
County,230,310,230,600,280
NoOfMonths_PartACov,12,12,12,12,12
NoOfMonths_PartBCov,12,12,12,12,12
ChronicCond_Alzheimer,1,1,1,2,2
ChronicCond_Heartfailure,2,1,1,2,1
ChronicCond_KidneyDisease,1,1,1,2,2
ChronicCond_Cancer,2,2,2,2,2
ChronicCond_ObstrPulmonary,2,2,1,2,1
ChronicCond_Depression,1,2,2,2,2
ChronicCond_Diabetes,1,2,2,2,1
ChronicCond_IschemicHeart,1,1,1,1,1
ChronicCond_Osteoporasis,2,2,2,1,1
ChronicCond_rheumatoidarthritis,1,2,2,2,1
ChronicCond_stroke,1,2,2,2,2
IPAnnualReimbursementAmt,36000,24000,19000,17000,27000
IPAnnualDeductibleAmt,3204,2136,1068,1068,2136
OPAnnualReimbursementAmt,60,450,100,1050,450
OPAnnualDeductibleAmt,70,200,20,540,160
PotentialFraud,Yes,Yes,Yes,Yes,Yes

In [ ]:
level binarizer

In [35]:
final_data['PotentialFraud'].value_counts()/len(final_data)*100

No     61.878931
Yes    38.121069
Name: PotentialFraud, dtype: float64

In [36]:
final_data['PotentialFraud'].value_counts(normalize = True)*100

No     61.878931
Yes    38.121069
Name: PotentialFraud, dtype: float64

In [37]:
for col in final_data.columns.tolist():
    print(final_data[col].value_counts())

BENE42721     29
BENE118316    29
BENE59303     29
BENE36330     28
BENE80977     28
              ..
BENE137989     1
BENE14133      1
BENE30070      1
BENE84103      1
BENE33372      1
Name: BeneID, Length: 138556, dtype: int64
CLM634921    1
CLM453735    1
CLM276715    1
CLM134856    1
CLM398192    1
            ..
CLM330641    1
CLM77601     1
CLM472808    1
CLM547967    1
CLM667175    1
Name: ClaimID, Length: 558211, dtype: int64
3/3/2009      1574
3/21/2009     1567
1/31/2009     1566
4/25/2009     1550
2/16/2009     1549
              ...
2008-11-28       2
2008-12-10       1
2009-12-31       1
2008-12-03       1
2008-12-06       1
Name: ClaimStartDt, Length: 783, dtype: int64
3/3/2009      1563
3/21/2009     1561
4/23/2009     1554
5/1/2009      1548
6/20/2009     1542
              ...
2009-11-29      82
2009-10-19      79
2009-11-11      77
2009-12-25      75
12/28/2008       1
Name: ClaimEndDt, Length: 731, dtype: int64
PRV51459    8240
PRV53797    4739
PRV51574    4444
PRV53918    3588
PRV54895    3436
            ...
PRV54304       1
PRV56339       1
PRV52537       1
PRV56286       1
PRV54621       1
Name: Provider, Length: 5410, dtype: int64
100      52960
10       42463
200      41634
60       40764
30       33920
         ...
8070         1
8300         1
2480         1
17100        1
10050        1
Name: InscClaimAmtReimbursed, Length: 438, dtype: int64
PHY330576    2534
PHY350277    1628
PHY412132    1321
PHY423534    1223
PHY314027    1200
             ...
PHY413819       1
PHY365704       1
PHY398100       1
PHY316502       1
PHY344463       1
Name: AttendingPhysician, Length: 82063, dtype: int64
PHY330576    424
PHY424897    293
PHY314027    256
PHY423534    250
PHY357120    249
            ...
PHY429554      1
PHY334211      1
PHY377008      1
PHY380236      1
PHY360535      1
Name: OperatingPhysician, Length: 35315, dtype: int64
PHY412132    1247
PHY341578    1098
PHY338032    1070
PHY337425    1041
PHY347064     806
             ...
PHY352571       1
PHY383505       1
PHY415137       1
PHY377665       1
PHY360535       1
Name: OtherPhysician, Length: 46457, dtype: int64
2009-02-10    144
2009-01-31    143
2009-02-26    143
2009-01-06    140
2009-02-02    138
             ...
2008-11-27      2
2008-12-10      1
2008-12-03      1
2008-12-06      1
2009-12-31      1
Name: AdmissionDt, Length: 398, dtype: int64
V7612    4074
42731    3634
78605    2992
4019     2732
25000    2368
         ...
4250        1
37023       1
56738       1
3061        1
7013        1
Name: ClmAdmitDiagnosisCode, Length: 4102, dtype: int64
0.0       496701
1068.0     39575
100.0       4582
70.0        2420
60.0        2065
40.0        2045
80.0        2024
50.0        1969
20.0        1406
30.0        1336
90.0        1245
10.0        1203
200.0        734
897.0          2
876.0          2
865.0          2
886.0          1
Name: DeductibleAmtPaid, dtype: int64
2009-02-11    153
2009-01-10    147
2009-03-03    143
2009-04-11    141
2009-06-17    138
             ...
2009-11-03     82
2009-12-23     82
2009-10-19     79
2009-11-11     77
2009-12-25     75
Name: DischargeDt, Length: 365, dtype: int64
882    179
884    174
166    168
183    165
939    163
      ...
927      1
775      1
934      1
765      1
768      1
Name: DiagnosisGroupCode, Length: 736, dtype: int64
4019     13886
4011     12512
2724      3606
2720      3210
2722      3028
         ...
64080        1
9523         1
E9506        1
6179         1
74343        1
Name: ClmDiagnosisCode_1, Length: 10371, dtype: int64
4019     22378
25000    11744
2724     11272
V5861     9716
V5869     9669
         ...
7489         1
36282        1
67454        1
3971         1
64683        1
Name: ClmDiagnosisCode_2, Length: 5326, dtype: int64
4019     14408
25000     7946
2724      7368
V5869     6069
V5861     4180
         ...
36477        1
43840        1
1338         1
82031        1
62132        1
Name: ClmDiagnosisCode_3, Length: 4790, dtype: int64
4019     9188
25000    5250
2724     4764
V5869    3367
2449     2523
         ...
6227        1
25083       1
71999       1
V1040       1
30471       1
Name: ClmDiagnosisCode_4, Length: 4392, dtype: int64
4019     6005
25000    3451
2724     2945
V5869    1921
2449     1647
         ...
7593        1
9080        1
V239        1
85300       1
36254       1
Name: ClmDiagnosisCode_5, Length: 3997, dtype: int64
4019     4170
25000    2506
2724     2072
42731    1312
53081    1248
         ...
1420        1
29644       1
V6120       1
56941       1
36254       1
Name: ClmDiagnosisCode_6, Length: 3640, dtype: int64
4019     3014
25000    1822
2724     1536
42731    1026
53081    1002
         ...
7014        1
5644        1
1420        1
V6120       1
V748        1
Name: ClmDiagnosisCode_7, Length: 3415, dtype: int64
4019     2257
25000    1399
2724     1178
42731     809
4280      795
         ...
V1781       1
41081       1
V4360       1
1368        1
36254       1
Name: ClmDiagnosisCode_8, Length: 3093, dtype: int64
4019     1581
25000    1100
2724      922
4280      665
42731     652
         ...
1624        1
5963        1
V7286       1
V5332       1
3862        1
Name: ClmDiagnosisCode_9, Length: 2797, dtype: int64
4019     169
25000    125
2724     100
4280      88
53081     78
        ...
9961       1
9972       1
40211      1
2396       1
30471      1
Name: ClmDiagnosisCode_10, Length: 1160, dtype: int64
9904.0    1152
8154.0    1022
66.0       900
3893.0     854
3995.0     809
          ...
5091.0       1
9972.0       1
9978.0       1
9992.0       1
4040.0       1
Name: ClmProcedureCode_1, Length: 1117, dtype: int64
4019.0    1736
2724.0     843
5849.0     291
311.0      152
2762.0     143
          ...
5111.0       1
4959.0       1
4871.0       1
4829.0       1
1175.0       1
Name: ClmProcedureCode_2, Length: 300, dtype: int64
4019.0    201
2724.0    192
5849.0     42
4439.0     29
9971.0     27
         ...
1509.0      1
400.0       1
1622.0      1
6822.0      1
4532.0      1
Name: ClmProcedureCode_3, Length: 154, dtype: int64
4019.0    18
2724.0    16
4439.0     7
4139.0     6
5849.0     6
3572.0     4
2762.0     4
4011.0     3
311.0      3
5185.0     3
496.0      2
4422.0     2
3320.0     2
9974.0     2
2763.0     2
5845.0     2
7804.0     2
42.0       2
7840.0     2
185.0      2
2761.0     1
3343.0     1
2752.0     1
2749.0     1
3844.0     1
3849.0     1
3962.0     1
3963.0     1
9986.0     1
7999.0     1
4104.0     1
4240.0     1
7851.0     1
7824.0     1
7823.0     1
7802.0     1
6822.0     1
412.0      1
1511.0     1
5789.0     1
5771.0     1
5121.0     1
5119.0     1
4660.0     1
1122.0     1
4414.0     1
4263.0     1
4269.0     1
Name: ClmProcedureCode_4, dtype: int64
4139.0    3
2724.0    2
5185.0    1
4422.0    1
9982.0    1
9971.0    1
Name: ClmProcedureCode_5, dtype: int64
Series([], Name: ClmProcedureCode_6, dtype: int64)
1943-12-01    2072
1939-03-01    2030
1942-10-01    1989
1939-04-01    1984
1938-09-01    1971
              ...
1980-05-01      28
1979-01-01      26
1983-02-01      24
1978-04-01      21
1983-03-01      20
Name: DOB, Length: 900, dtype: int64
2009-12-01    710
2009-10-01    572
2009-11-01    560
2009-09-01    511
2009-08-01    482
2009-07-01    371
2009-06-01    295
2009-05-01    243
2009-04-01    166
2009-03-01    157
2009-02-01     64
Name: DOD, dtype: int64
2    323114
1    235097
Name: Gender, dtype: int64
1    471036
2     55640
3     19715
5     11820
Name: Race, dtype: int64
0    448363
Y    109848
Name: RenalDiseaseIndicator, dtype: int64
5     51350
10    39073
33    35024
45    34022
14    24417
39    24251
23    21343
36    21291
34    18905
11    17003
31    15940
49    14997
44    14418
15    14213
22    13624
26    12911
50    11740
21    11261
42    10491
18    10322
1     10240
52     9792
3      9344
19     7917
24     7726
4      7571
16     7457
6      7200
37     6990
25     6682
7      5617
38     5518
17     4884
51     4644
54     4233
28     4168
20     3833
32     3456
46     3381
13     2765
30     2654
43     2002
27     1995
29     1978
47     1827
12     1706
8      1530
41     1110
53     1098
35      940
2       738
9       619
Name: State, dtype: int64
200    15957
10     13982
20     12632
470    12278
60     11995
       ...
944        2
742        2
834        1
521        1
804        1
Name: County, Length: 314, dtype: int64
12    554722
0       2971
6        116
8        100
11        81
4         55
7         44
10        34
5         30
3         16
2         16
9         13
1         13
Name: NoOfMonths_PartACov, dtype: int64
12    553918
0       1979
6        728
10       402
11       313
9        242
8        142
7        139
5        126
3         73
4         60
1         48
2         41
Name: NoOfMonths_PartBCov, dtype: int64
2    333884
1    224327
Name: ChronicCond_Alzheimer, dtype: int64
1    329583
2    228628
Name: ChronicCond_Heartfailure, dtype: int64
2    328227
1    229984
Name: ChronicCond_KidneyDisease, dtype: int64
2    473706
1     84505
Name: ChronicCond_Cancer, dtype: int64
2    383530
1    174681
Name: ChronicCond_ObstrPulmonary, dtype: int64
2    315497
1    242714
Name: ChronicCond_Depression, dtype: int64
1    393759
2    164452
Name: ChronicCond_Diabetes, dtype: int64
1    423830
2    134381
Name: ChronicCond_IschemicHeart, dtype: int64
2    380897
1    177314
Name: ChronicCond_Osteoporasis, dtype: int64
2    384512
1    173699
Name: ChronicCond_rheumatoidarthritis, dtype: int64
2    501430
1     56781
Name: ChronicCond_stroke, dtype: int64

0         371676
4000        9909
5000        8822
3000        8301
6000        7506
           ...
23500          1
57510          1
31050          1
2110           1
101120         1
Name: IPAnnualReimbursementAmt, Length: 3004, dtype: int64
0        369267
1068     125646
2136      40454
3204      11730
4272       3420
          ...
37204         3
10436         2
14068         2
9408          1
1118          1
Name: IPAnnualDeductibleAmt, Length: 147, dtype: int64
 100      5950
 200      5443
 0        4918
 300      4578
 400      4318
          ...
 14510       1
 32710       1
 9020        1
 24870       1
-40          1
Name: OPAnnualReimbursementAmt, Length: 2078, dtype: int64
0       20131
20      14295
100     11939
30      11195
10      11175
        ...
2108        2
9130        2
897         2
1197        2
3860        2
Name: OPAnnualDeductibleAmt, Length: 789, dtype: int64
No     345415
Yes    212796
Name: PotentialFraud, dtype: int64

In [38]:
final_data['ClmProcedureCode_6'].value_counts() #col 2 be removed

Series([], Name: ClmProcedureCode_6, dtype: int64)

In [ ]:
#Feature engineering and data pre-processing

In [39]:
inpatient_data.shape

(40474, 30)

In [43]:
inpatient_data['Provider'].nunique()

2092

In [40]:
train.shape

(5410, 2)

In [54]:
train_inpatient = pd.merge(inpatient_data, train, how = "outer", on = 'Provider')

In [55]:
train_inpatient.shape

(43792, 31)

In [60]:
non_inpatient = np.setdiff1d(np.array(train['Provider']), np.array(inpatient_data['Provider']))

In [61]:
len(non_inpatient)

3318

In [62]:
non_inpatient

array(['PRV51004', 'PRV51005', 'PRV51012', ..., 'PRV57761', 'PRV57762',
       'PRV57763'], dtype=object)

In [47]:
5410 - 2092 + 40474

43792

In [51]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes

In [49]:
train_inpatient['PotentialFraud'].value_counts()

Yes    23468
No     20324
Name: PotentialFraud, dtype: int64

In [63]:
train_inpatient[train_inpatient['Provider'] == 'PRV51004']

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud
40474,NaN,NaN,NaN,NaN,PRV51004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No

In [64]:
train_outpatient = pd.merge(outpatient_data, train, how = "outer", on = 'Provider')

In [65]:
train_outpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode,PotentialFraud
0,BENE11002,CLM624349,10/11/2009,10/11/2009,PRV56011,30.0,PHY326117,NaN,NaN,78943,V5866,V1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,56409,Yes
1,BENE11004,CLM121801,1/6/2009,1/6/2009,PRV56011,40.0,PHY334319,NaN,NaN,71988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes
2,BENE11004,CLM150998,1/22/2009,1/22/2009,PRV56011,200.0,PHY403831,NaN,NaN,82382,30000,72887,4280,7197,V4577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,71947,Yes
3,BENE11004,CLM173224,2/3/2009,2/3/2009,PRV56011,20.0,PHY339887,NaN,NaN,20381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes
4,BENE11004,CLM224741,3/3/2009,3/3/2009,PRV56011,40.0,PHY345721,NaN,NaN,V6546,4280,2449,V854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes

In [66]:
outpatient_data.shape

(517737, 27)

In [67]:
train.shape

(5410, 2)

In [68]:
train_outpatient.shape

(518135, 28)

In [69]:
final_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,PHY327147,NaN,NaN,NaN,0.0,NaN,NaN,V7183,53081,78959,4280,E8788,78079,79902,25002,71848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1932-05-01,NaN,1,1,0,39,310,12,12,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,1913-12-01,NaN,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,1922-10-01,NaN,1,1,0,39,600,12,12,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,1930-07-01,NaN,2,1,0,39,280,12,12,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes

In [73]:
#series to dictionary
physician_count = final_data['AttendingPhysician'].value_counts().to_dict()

In [74]:
physician_count

{'PHY330576': 2534,
 'PHY350277': 1628,
 'PHY412132': 1321,
 'PHY423534': 1223,
 'PHY314027': 1200,
 'PHY327046': 1181,
 'PHY338032': 1158,
 'PHY337425': 1156,
 'PHY357120': 1156,
 'PHY341578': 1133,
 'PHY432650': 1093,
 'PHY347064': 1076,
 'PHY351121': 1053,
 'PHY383481': 1005,
 'PHY415321': 1002,
 'PHY344389': 1000,
 'PHY433436': 924,
 'PHY375943': 912,
 'PHY375453': 880,
 'PHY387126': 762,
 'PHY357307': 737,
 'PHY432614': 716,
 'PHY318667': 711,
 'PHY424712': 693,
 'PHY326984': 686,
 'PHY347780': 678,
 'PHY362889': 674,
 'PHY313278': 674,
 'PHY389456': 673,
 'PHY323447': 664,
 'PHY387026': 647,
 'PHY368630': 637,
 'PHY333735': 634,
 'PHY367255': 634,
 'PHY360043': 627,
 'PHY373032': 618,
 'PHY381249': 615,
 'PHY375219': 609,
 'PHY356444': 600,
 'PHY404832': 596,
 'PHY418434': 585,
 'PHY360179': 583,
 'PHY385072': 582,
 'PHY339530': 569,
 'PHY341452': 561,
 'PHY325906': 547,
 'PHY405720': 544,
 'PHY350610': 535,
 'PHY362200': 528,
 'PHY387900': 514,
 'PHY430054': 513,
 'PHY416732': 504,
 'PHY342223': 503,
 'PHY396637': 503,
 'PHY329600': 503,
 'PHY383336': 502,
 'PHY407400': 501,
 'PHY386363': 500,
 'PHY421058': 499,
 'PHY410597': 490,
 'PHY433374': 483,
 'PHY369122': 482,
 'PHY418441': 481,
 'PHY412121': 480,
 'PHY387395': 479,
 'PHY422181': 478,
 'PHY392264': 476,
 'PHY409965': 475,
 'PHY315358': 474,
 'PHY361063': 470,
 'PHY344257': 464,
 'PHY342375': 463,
 'PHY388040': 447,
 'PHY326049': 445,
 'PHY341768': 436,
 'PHY403755': 429,
 'PHY351973': 426,
 'PHY352555': 424,
 'PHY318242': 422,
 'PHY356051': 404,
 'PHY328307': 402,
 'PHY353823': 389,
 'PHY422134': 386,
 'PHY423941': 376,
 'PHY322775': 372,
 'PHY335375': 367,
 'PHY374226': 363,
 'PHY363575': 348,
 'PHY424939': 347,
 'PHY415621': 346,
 'PHY405650': 344,
 'PHY366914': 333,
 'PHY394276': 331,
 'PHY340260': 328,
 'PHY423304': 327,
 'PHY319973': 326,
 'PHY341671': 323,
 'PHY377766': 322,
 'PHY422235': 321,
 'PHY313818': 319,
 'PHY311788': 316,
 'PHY342753': 315,
 'PHY354739': 307,
 'PHY388477': 304,
 'PHY342582': 302,
 'PHY354326': 301,
 'PHY328613': 300,
 'PHY348408': 299,
 'PHY345497': 298,
 'PHY426654': 298,
 'PHY420028': 289,
 'PHY365595': 289,
 'PHY324335': 287,
 'PHY376936': 284,
 'PHY427186': 282,
 'PHY388996': 282,
 'PHY333981': 281,
 'PHY368638': 281,
 'PHY429147': 280,
 'PHY312018': 279,
 'PHY425169': 279,
 'PHY385898': 279,
 'PHY341325': 278,
 'PHY377552': 278,
 'PHY410865': 277,
 'PHY371576': 277,
 'PHY341560': 274,
 'PHY352753': 272,
 'PHY334905': 271,
 'PHY338662': 270,
 'PHY363309': 269,
 'PHY319039': 269,
 'PHY349909': 267,
 'PHY366501': 267,
 'PHY366755': 266,
 'PHY373858': 265,
 'PHY422260': 264,
 'PHY422483': 260,
 'PHY341041': 259,
 'PHY428634': 258,
 'PHY359164': 257,
 'PHY396580': 257,
 'PHY319349': 257,
 'PHY351443': 257,
 'PHY347629': 256,
 'PHY351338': 256,
 'PHY344239': 252,
 'PHY332888': 251,
 'PHY383820': 251,
 'PHY379935': 250,
 'PHY367158': 247,
 'PHY410752': 245,
 'PHY359122': 245,
 'PHY406155': 244,
 'PHY357909': 241,
 'PHY399975': 241,
 'PHY354938': 238,
 'PHY422728': 236,
 'PHY405860': 235,
 'PHY326286': 234,
 'PHY380757': 233,
 'PHY426553': 232,
 'PHY385474': 232,
 'PHY347925': 231,
 'PHY405937': 231,
 'PHY360244': 230,
 'PHY328402': 230,
 'PHY397870': 229,
 'PHY360271': 227,
 'PHY372623': 226,
 'PHY384948': 226,
 'PHY327964': 226,
 'PHY341928': 226,
 'PHY429080': 225,
 'PHY315344': 224,
 'PHY365930': 223,
 'PHY402457': 222,
 'PHY388358': 221,
 'PHY399829': 221,
 'PHY319816': 220,
 'PHY327386': 219,
 'PHY314587': 219,
 'PHY332810': 219,
 'PHY423761': 219,
 'PHY315424': 219,
 'PHY370745': 218,
 'PHY316099': 218,
 'PHY367916': 217,
 'PHY425984': 217,
 'PHY395822': 216,
 'PHY402093': 216,
 'PHY356538': 216,
 'PHY423641': 214,
 'PHY332626': 214,
 'PHY326637': 211,
 'PHY326733': 210,
 'PHY402355': 210,
 'PHY342906': 209,
 'PHY345861': 209,
 'PHY315112': 209,
 'PHY424985': 209,
 'PHY361612': 208,
 'PHY326003': 208,
 'PHY378955': 207,
 'PHY371562': 207,
 'PHY364025': 206,
 'PHY340021': 205,
 'PHY374189': 204,
 'PHY326162': 203,
 'PHY321907': 203,
 'PHY380919': 201,
 'PHY353553': 201,
 'PHY312247': 200,
 'PHY357131': 200,
 'PHY394232': 199,
 'PHY349756': 199,
 'PHY339042': 198,
 'PHY411541': 198,
 'PHY397149': 197,
 'PHY313705': 197,
 'PHY354885': 197,
 'PHY397375': 197,
 'PHY427441': 196,
 'PHY383305': 196,
 'PHY337092': 196,
 'PHY362864': 195,
 'PHY431177': 195,
 'PHY339873': 194,
 'PHY349182': 193,
 'PHY337335': 193,
 'PHY353097': 192,
 'PHY348872': 190,
 'PHY345071': 190,
 'PHY358873': 190,
 'PHY389847': 190,
 'PHY374305': 189,
 'PHY355600': 188,
 'PHY368882': 188,
 'PHY396617': 188,
 'PHY387249': 187,
 'PHY356104': 186,
 'PHY371725': 184,
 'PHY398810': 183,
 'PHY338597': 183,
 'PHY372364': 183,
 'PHY354374': 183,
 'PHY428858': 180,
 'PHY424276': 180,
 'PHY429938': 180,
 'PHY323501': 180,
 'PHY413439': 180,
 'PHY330980': 180,
 'PHY384394': 179,
 'PHY345111': 179,
 'PHY339637': 179,
 'PHY411662': 179,
 'PHY424424': 178,
 'PHY373205': 178,
 'PHY405659': 178,
 'PHY381033': 178,
 'PHY349818': 178,
 'PHY367268': 178,
 'PHY317422': 178,
 'PHY317529': 177,
 'PHY384873': 177,
 'PHY317862': 176,
 'PHY333216': 175,
 'PHY360321': 175,
 'PHY416287': 175,
 'PHY371865': 174,
 'PHY314410': 173,
 'PHY378340': 173,
 'PHY364820': 172,
 'PHY324500': 171,
 'PHY344879': 170,
 'PHY412566': 170,
 'PHY411722': 169,
 'PHY429828': 168,
 'PHY422221': 168,
 'PHY418684': 167,
 'PHY364477': 167,
 'PHY318447': 167,
 'PHY400274': 167,
 'PHY347233': 167,
 'PHY412508': 166,
 'PHY313692': 166,
 'PHY371459': 165,
 'PHY430367': 164,
 'PHY391882': 164,
 'PHY401160': 163,
 'PHY348307': 163,
 'PHY352006': 162,
 'PHY376343': 162,
 'PHY422043': 162,
 'PHY329774': 161,
 'PHY396496': 161,
 'PHY405838': 160,
 'PHY416432': 160,
 'PHY429222': 160,
 'PHY327824': 160,
 'PHY407179': 160,
 'PHY390875': 160,
 'PHY346686': 160,
 'PHY430885': 159,
 'PHY433530': 159,
 'PHY315400': 158,
 'PHY404200': 158,
 'PHY331295': 158,
 'PHY312780': 158,
 'PHY313599': 157,
 'PHY393087': 157,
 'PHY366156': 156,
 'PHY358635': 156,
 'PHY348928': 156,
 'PHY349295': 155,
 'PHY401319': 155,
 'PHY392297': 154,
 'PHY311407': 154,
 'PHY433664': 154,
 'PHY404394': 154,
 'PHY371896': 154,
 'PHY425443': 154,
 'PHY335975': 154,
 'PHY368786': 153,
 'PHY324052': 153,
 'PHY354358': 152,
 'PHY365993': 152,
 'PHY333152': 151,
 'PHY344557': 151,
 'PHY407877': 150,
 'PHY347281': 150,
 'PHY345068': 150,
 'PHY406092': 150,
 'PHY382394': 150,
 'PHY339670': 149,
 'PHY346988': 149,
 'PHY408393': 149,
 'PHY317438': 149,
 'PHY346463': 149,
 'PHY392136': 149,
 'PHY420091': 149,
 'PHY433622': 149,
 'PHY429095': 148,
 'PHY391951': 148,
 'PHY429078': 148,
 'PHY395255': 147,
 'PHY413840': 147,
 'PHY426955': 147,
 'PHY423244': 147,
 'PHY358414': 147,
 'PHY384272': 147,
 'PHY356646': 147,
 'PHY338562': 146,
 'PHY358241': 146,
 'PHY376288': 145,
 'PHY342238': 145,
 'PHY380867': 145,
 'PHY381705': 145,
 'PHY428261': 144,
 'PHY384380': 144,
 'PHY388514': 144,
 'PHY429784': 144,
 'PHY361948': 143,
 'PHY389662': 143,
 'PHY355492': 143,
 'PHY340328': 143,
 'PHY337003': 143,
 'PHY327514': 143,
 'PHY425644': 142,
 'PHY346569': 142,
 'PHY396267': 142,
 'PHY429105': 142,
 'PHY393262': 141,
 'PHY321036': 141,
 'PHY412288': 141,
 'PHY406261': 141,
 'PHY351311': 140,
 'PHY332820': 140,
 'PHY352112': 140,
 'PHY425795': 140,
 'PHY380551': 139,
 'PHY419485': 139,
 'PHY416424': 139,
 'PHY375267': 139,
 'PHY393374': 139,
 'PHY320581': 139,
 'PHY335850': 139,
 'PHY359026': 138,
 'PHY333331': 138,
 'PHY402056': 138,
 'PHY347107': 138,
 'PHY360653': 138,
 'PHY426179': 138,
 'PHY311115': 138,
 'PHY417058': 137,
 'PHY372489': 137,
 'PHY378799': 137,
 'PHY327473': 137,
 'PHY414365': 137,
 'PHY379737': 137,
 'PHY337774': 137,
 'PHY414985': 137,
 'PHY348551': 137,
 'PHY359750': 137,
 'PHY418939': 137,
 'PHY376335': 136,
 'PHY432127': 136,
 'PHY431927': 136,
 'PHY336375': 136,
 'PHY315616': 136,
 'PHY377002': 135,
 'PHY412053': 135,
 'PHY352030': 135,
 'PHY412844': 135,
 'PHY344188': 135,
 'PHY331695': 135,
 'PHY351910': 135,
 'PHY349836': 135,
 'PHY375728': 135,
 'PHY337051': 135,
 'PHY406209': 134,
 'PHY432927': 134,
 'PHY417751': 134,
 'PHY389249': 134,
 'PHY405216': 134,
 'PHY341553': 133,
 'PHY319087': 133,
 'PHY433357': 133,
 'PHY346328': 133,
 'PHY427473': 133,
 'PHY343767': 133,
 'PHY403478': 133,
 'PHY405955': 132,
 'PHY363761': 132,
 'PHY389109': 132,
 'PHY403682': 132,
 'PHY382099': 132,
 'PHY411888': 132,
 'PHY312203': 132,
 'PHY367887': 132,
 'PHY378484': 131,
 'PHY429622': 131,
 'PHY415314': 131,
 'PHY335146': 131,
 'PHY377718': 130,
 'PHY324561': 130,
 'PHY388916': 130,
 'PHY321288': 130,
 'PHY390959': 130,
 'PHY416347': 130,
 'PHY391796': 130,
 'PHY373626': 130,
 'PHY370240': 129,
 'PHY346134': 129,
 'PHY373466': 129,
 'PHY408544': 129,
 'PHY393668': 129,
 'PHY347104': 129,
 'PHY362965': 128,
 'PHY388819': 128,
 'PHY406370': 128,
 'PHY410681': 128,
 'PHY421969': 128,
 'PHY419950': 127,
 'PHY352228': 127,
 'PHY423392': 127,
 'PHY376138': 127,
 'PHY401145': 127,
 'PHY394143': 127,
 'PHY344950': 126,
 'PHY355131': 126,
 'PHY403282': 126,
 'PHY419379': 126,
 'PHY325118': 126,
 'PHY433465': 126,
 'PHY344367': 126,
 'PHY406867': 125,
 'PHY412600': 125,
 'PHY357445': 125,
 'PHY375443': 125,
 'PHY426706': 125,
 'PHY347573': 125,
 'PHY314880': 125,
 'PHY378227': 125,
 'PHY392914': 125,
 'PHY422717': 124,
 'PHY347511': 124,
 'PHY419512': 124,
 'PHY369154': 124,
 'PHY343273': 124,
 'PHY374565': 124,
 'PHY383960': 124,
 'PHY372562': 123,
 'PHY368661': 123,
 'PHY397478': 123,
 'PHY388025': 123,
 'PHY413916': 123,
 'PHY321450': 123,
 'PHY430625': 123,
 'PHY428459': 123,
 'PHY411123': 122,
 'PHY358879': 122,
 'PHY342494': 122,
 'PHY338918': 122,
 'PHY327234': 122,
 'PHY364515': 121,
 'PHY399747': 121,
 'PHY406323': 121,
 'PHY318813': 121,
 'PHY350524': 121,
 'PHY319184': 121,
 'PHY313877': 121,
 'PHY322406': 121,
 'PHY419567': 121,
 'PHY312130': 120,
 'PHY331166': 120,
 'PHY419108': 120,
 'PHY429276': 120,
 'PHY426087': 120,
 'PHY433128': 120,
 'PHY321245': 119,
 'PHY358603': 119,
 'PHY377234': 119,
 'PHY314610': 119,
 'PHY373165': 119,
 'PHY430835': 119,
 'PHY418957': 119,
 'PHY322048': 119,
 'PHY339339': 119,
 'PHY320554': 118,
 'PHY321072': 118,
 'PHY430090': 118,
 'PHY330549': 118,
 'PHY394779': 118,
 'PHY420779': 118,
 'PHY409699': 118,
 'PHY332294': 117,
 'PHY423980': 117,
 'PHY380850': 117,
 'PHY380182': 117,
 'PHY333995': 117,
 'PHY377741': 117,
 'PHY316329': 116,
 'PHY342324': 116,
 'PHY385561': 116,
 'PHY339166': 116,
 'PHY365132': 116,
 'PHY327223': 116,
 'PHY361786': 116,
 'PHY428454': 115,
 'PHY427097': 115,
 'PHY378541': 115,
 'PHY363733': 115,
 'PHY391413': 115,
 'PHY318159': 115,
 'PHY364317': 115,
 'PHY398277': 114,
 'PHY414204': 114,
 'PHY382290': 114,
 'PHY359776': 114,
 'PHY376882': 114,
 'PHY407862': 114,
 'PHY385642': 114,
 'PHY360602': 114,
 'PHY332351': 113,
 'PHY340075': 113,
 'PHY433412': 113,
 'PHY346968': 113,
 'PHY373993': 113,
 'PHY362735': 113,
 'PHY394539': 113,
 'PHY353156': 113,
 'PHY421562': 113,
 'PHY355928': 113,
 'PHY403464': 113,
 'PHY427222': 113,
 'PHY425123': 113,
 'PHY410325': 113,
 'PHY317185': 113,
 'PHY338145': 112,
 'PHY406201': 112,
 'PHY352454': 112,
 'PHY375972': 112,
 'PHY411545': 112,
 'PHY400373': 112,
 'PHY423833': 112,
 'PHY314408': 112,
 'PHY415142': 112,
 'PHY420625': 111,
 'PHY433915': 111,
 'PHY395758': 111,
 'PHY370524': 111,
 'PHY390148': 111,
 'PHY371931': 111,
 'PHY396224': 111,
 'PHY357709': 111,
 'PHY402362': 111,
 'PHY427886': 111,
 'PHY348245': 110,
 'PHY321331': 110,
 'PHY338552': 110,
 'PHY423019': 110,
 'PHY361370': 110,
 'PHY376446': 110,
 'PHY330089': 110,
 'PHY398111': 110,
 'PHY421149': 110,
 'PHY385695': 109,
 'PHY333980': 109,
 'PHY423877': 109,
 'PHY322586': 109,
 'PHY337890': 109,
 'PHY429887': 109,
 'PHY359290': 109,
 'PHY415911': 109,
 'PHY416112': 109,
 'PHY384809': 109,
 'PHY357108': 109,
 'PHY315807': 108,
 'PHY384216': 108,
 'PHY318302': 108,
 'PHY358865': 108,
 'PHY346000': 108,
 'PHY315287': 108,
 'PHY327943': 108,
 'PHY358460': 108,
 'PHY374128': 108,
 'PHY430053': 107,
 'PHY384441': 107,
 'PHY403576': 107,
 'PHY402094': 107,
 'PHY368454': 107,
 'PHY330571': 107,
 'PHY315692': 107,
 'PHY331636': 106,
 'PHY407165': 106,
 'PHY324916': 106,
 'PHY422994': 106,
 'PHY337968': 106,
 'PHY353688': 106,
 'PHY317521': 105,
 'PHY386498': 105,
 'PHY334590': 105,
 'PHY347029': 105,
 'PHY352963': 105,
 'PHY330845': 105,
 'PHY338690': 105,
 'PHY394748': 105,
 'PHY340012': 105,
 'PHY322149': 105,
 'PHY404352': 105,
 'PHY416865': 105,
 'PHY353241': 105,
 'PHY389133': 104,
 'PHY331724': 104,
 'PHY340150': 104,
 'PHY433122': 104,
 'PHY360262': 104,
 'PHY411809': 104,
 'PHY394727': 104,
 'PHY416093': 104,
 'PHY405990': 104,
 'PHY423848': 104,
 'PHY342066': 104,
 'PHY413169': 104,
 'PHY325176': 104,
 'PHY412628': 104,
 'PHY433627': 103,
 'PHY365681': 103,
 'PHY424811': 103,
 'PHY370785': 103,
 'PHY343438': 103,
 'PHY376933': 103,
 'PHY312479': 103,
 'PHY370327': 103,
 'PHY363225': 103,
 'PHY376059': 103,
 'PHY348703': 103,
 'PHY331728': 102,
 'PHY410385': 102,
 'PHY374394': 102,
 'PHY328472': 102,
 'PHY316950': 102,
 'PHY338169': 102,
 'PHY386158': 102,
 'PHY367901': 102,
 'PHY358193': 101,
 'PHY351291': 101,
 'PHY377118': 101,
 'PHY409755': 101,
 'PHY359424': 101,
 'PHY372510': 101,
 'PHY367356': 101,
 'PHY378732': 101,
 'PHY381098': 101,
 'PHY420521': 101,
 'PHY412356': 100,
 'PHY374426': 100,
 'PHY411281': 100,
 'PHY348953': 100,
 'PHY385113': 100,
 'PHY388989': 100,
 'PHY330109': 100,
 'PHY365755': 100,
 'PHY312439': 100,
 'PHY345634': 99,
 'PHY322853': 99,
 'PHY380510': 99,
 'PHY377389': 99,
 'PHY369551': 98,
 'PHY392596': 98,
 'PHY320956': 98,
 'PHY379217': 98,
 'PHY331450': 98,
 'PHY316028': 98,
 'PHY414843': 98,
 'PHY340839': 98,
 'PHY338431': 98,
 'PHY355134': 98,
 'PHY315964': 98,
 'PHY389217': 98,
 'PHY401995': 98,
 'PHY402937': 98,
 'PHY359433': 97,
 'PHY369119': 97,
 'PHY313127': 97,
 'PHY321957': 97,
 'PHY354114': 97,
 'PHY351002': 97,
 'PHY348748': 97,
 'PHY416938': 97,
 'PHY330830': 97,
 'PHY351829': 97,
 'PHY314546': 97,
 'PHY370342': 97,
 'PHY345412': 97,
 'PHY433037': 97,
 'PHY356058': 97,
 'PHY415299': 97,
 'PHY404831': 97,
 'PHY353128': 96,
 'PHY359586': 96,
 'PHY342688': 96,
 'PHY415031': 96,
 'PHY367568': 96,
 'PHY326594': 96,
 'PHY385509': 96,
 'PHY358451': 96,
 'PHY315436': 96,
 'PHY355996': 96,
 'PHY412342': 96,
 'PHY403331': 96,
 'PHY371133': 96,
 'PHY401920': 96,
 'PHY328355': 96,
 'PHY329192': 96,
 'PHY390618': 96,
 'PHY396507': 96,
 'PHY321587': 95,
 'PHY393720': 95,
 'PHY415330': 95,
 'PHY357270': 95,
 'PHY369553': 95,
 'PHY362642': 95,
 'PHY341082': 95,
 'PHY378468': 95,
 'PHY334014': 95,
 'PHY380813': 95,
 'PHY394788': 95,
 'PHY348290': 95,
 'PHY340136': 95,
 'PHY326889': 95,
 'PHY420323': 95,
 'PHY321111': 95,
 'PHY427802': 94,
 'PHY377712': 94,
 'PHY425597': 94,
 'PHY406546': 94,
 'PHY339242': 94,
 'PHY371507': 94,
 'PHY383017': 94,
 'PHY403570': 94,
 'PHY393303': 94,
 'PHY357100': 94,
 'PHY411165': 94,
 'PHY428093': 94,
 'PHY328384': 94,
 'PHY402328': 94,
 'PHY391158': 94,
 'PHY373682': 94,
 'PHY376184': 94,
 'PHY419136': 93,
 'PHY389327': 93,
 'PHY314320': 93,
 'PHY381513': 93,
 'PHY360727': 93,
 'PHY414120': 93,
 'PHY320350': 93,
 'PHY365057': 93,
 'PHY399966': 93,
 'PHY410899': 93,
 'PHY360510': 93,
 'PHY364398': 93,
 'PHY383351': 93,
 'PHY427881': 93,
 'PHY316159': 93,
 'PHY421242': 93,
 'PHY424890': 93,
 'PHY322184': 93,
 'PHY416867': 92,
 'PHY389178': 92,
 'PHY392554': 92,
 'PHY330784': 92,
 'PHY378391': 92,
 'PHY415219': 92,
 'PHY400422': 92,
 'PHY415041': 92,
 'PHY345502': 92,
 'PHY365445': 92,
 'PHY379247': 92,
 'PHY320280': 92,
 'PHY426097': 92,
 'PHY399392': 92,
 'PHY377253': 92,
 'PHY433463': 92,
 'PHY367783': 92,
 'PHY342344': 92,
 'PHY331484': 91,
 'PHY367249': 91,
 'PHY397520': 91,
 'PHY361771': 91,
 'PHY338803': 91,
 'PHY311343': 91,
 'PHY359280': 91,
 'PHY389988': 91,
 'PHY382047': 91,
 'PHY403529': 91,
 'PHY325821': 91,
 'PHY402679': 91,
 'PHY329324': 91,
 'PHY411660': 91,
 'PHY383763': 91,
 'PHY330328': 91,
 'PHY382592': 91,
 'PHY400712': 91,
 'PHY377680': 90,
 'PHY387351': 90,
 'PHY360056': 90,
 'PHY410213': 90,
 'PHY382688': 90,
 'PHY358767': 90,
 'PHY399458': 90,
 'PHY425365': 90,
 'PHY357933': 90,
 'PHY347720': 90,
 'PHY400120': 90,
 'PHY404797': 90,
 'PHY365507': 90,
 'PHY325000': 90,
 'PHY351257': 90,
 'PHY369804': 89,
 'PHY406981': 89,
 'PHY398500': 89,
 'PHY323130': 89,
 'PHY344222': 89,
 'PHY329009': 89,
 'PHY324355': 88,
 'PHY367788': 88,
 'PHY357741': 88,
 'PHY365422': 88,
 'PHY341780': 88,
 'PHY424785': 88,
 'PHY399312': 88,
 'PHY388675': 88,
 'PHY389236': 88,
 'PHY354238': 88,
 'PHY389434': 88,
 'PHY412706': 88,
 'PHY320707': 88,
 'PHY357652': 87,
 'PHY336226': 87,
 'PHY360107': 87,
 'PHY412631': 87,
 'PHY416617': 87,
 'PHY406084': 87,
 'PHY358392': 87,
 'PHY398587': 87,
 'PHY373854': 87,
 'PHY425585': 87,
 'PHY394725': 87,
 'PHY410831': 87,
 'PHY428150': 86,
 'PHY351463': 86,
 'PHY346176': 86,
 'PHY414961': 86,
 'PHY354646': 86,
 'PHY367162': 86,
 'PHY338413': 86,
 'PHY332284': 86,
 'PHY358427': 86,
 'PHY348301': 86,
 'PHY321417': 86,
 'PHY429478': 86,
 'PHY421576': 85,
 'PHY422853': 85,
 'PHY334461': 85,
 'PHY335023': 85,
 'PHY316244': 85,
 'PHY322883': 85,
 'PHY340158': 85,
 'PHY377950': 85,
 'PHY397865': 85,
 'PHY411639': 85,
 'PHY380691': 85,
 'PHY312676': 85,
 'PHY318525': 85,
 'PHY382285': 85,
 'PHY391459': 85,
 'PHY396630': 85,
 'PHY373377': 85,
 'PHY376573': 84,
 'PHY408720': 84,
 'PHY348617': 84,
 'PHY378110': 84,
 'PHY347006': 84,
 'PHY393928': 84,
 'PHY321347': 84,
 'PHY334243': 84,
 'PHY324491': 84,
 'PHY418459': 84,
 'PHY415375': 84,
 'PHY383955': 84,
 'PHY340634': 84,
 'PHY413509': 84,
 'PHY412980': 84,
 'PHY375509': 84,
 'PHY372925': 84,
 'PHY347380': 83,
 'PHY353878': 83,
 'PHY344762': 83,
 'PHY386012': 83,
 'PHY424943': 83,
 'PHY377709': 83,
 'PHY388481': 83,
 'PHY387189': 83,
 'PHY432603': 83,
 'PHY315576': 83,
 'PHY427880': 83,
 'PHY359821': 83,
 'PHY412513': 83,
 'PHY325883': 83,
 'PHY410411': 83,
 'PHY423718': 83,
 'PHY429708': 83,
 'PHY387032': 83,
 'PHY314482': 83,
 'PHY334665': 83,
 'PHY318773': 83,
 'PHY329121': 82,
 'PHY432396': 82,
 'PHY332706': 82,
 'PHY334319': 82,
 'PHY375024': 82,
 'PHY340413': 82,
 'PHY404722': 82,
 'PHY329852': 82,
 'PHY406024': 82,
 'PHY430789': 82,
 'PHY380633': 82,
 'PHY371264': 82,
 'PHY373855': 82,
 'PHY378127': 82,
 'PHY324021': 82,
 'PHY370629': 82,
 'PHY382517': 82,
 'PHY341726': 82,
 'PHY315076': 82,
 'PHY385446': 82,
 'PHY397815': 82,
 'PHY392020': 81,
 'PHY360481': 81,
 'PHY416674': 81,
 'PHY345836': 81,
 'PHY379482': 81,
 'PHY417809': 81,
 'PHY342806': 81,
 'PHY360035': 81,
 'PHY341068': 81,
 'PHY365427': 81,
 'PHY316253': 81,
 'PHY430465': 81,
 'PHY398033': 81,
 'PHY355678': 81,
 'PHY403443': 81,
 'PHY386547': 80,
 'PHY402729': 80,
 'PHY416193': 80,
 'PHY377998': 80,
 'PHY417420': 80,
 'PHY337089': 80,
 ...}

In [75]:
provider_count = final_data['Provider'].value_counts().to_dict()

In [76]:
provider_count

{'PRV51459': 8240,
 'PRV53797': 4739,
 'PRV51574': 4444,
 'PRV53918': 3588,
 'PRV54895': 3436,
 'PRV55215': 3393,
 'PRV52064': 2844,
 'PRV56011': 2833,
 'PRV55004': 2399,
 'PRV57306': 2315,
 'PRV56560': 2313,
 'PRV52030': 2275,
 'PRV52649': 2156,
 'PRV54772': 2115,
 'PRV52628': 2098,
 'PRV51369': 2083,
 'PRV51347': 2067,
 'PRV55039': 2058,
 'PRV57103': 2049,
 'PRV52019': 1961,
 'PRV51480': 1924,
 'PRV55462': 1907,
 'PRV55467': 1896,
 'PRV54742': 1892,
 'PRV52041': 1885,
 'PRV54837': 1843,
 'PRV54966': 1796,
 'PRV56689': 1794,
 'PRV51836': 1794,
 'PRV57172': 1760,
 'PRV52340': 1743,
 'PRV54778': 1672,
 'PRV51567': 1632,
 'PRV54372': 1617,
 'PRV51433': 1610,
 'PRV56416': 1592,
 'PRV54075': 1519,
 'PRV51578': 1500,
 'PRV57191': 1500,
 'PRV54350': 1495,
 'PRV54070': 1467,
 'PRV52066': 1455,
 'PRV51244': 1415,
 'PRV52985': 1403,
 'PRV53786': 1382,
 'PRV54939': 1380,
 'PRV56008': 1370,
 'PRV56442': 1330,
 'PRV56444': 1317,
 'PRV54786': 1316,
 'PRV55977': 1302,
 'PRV52059': 1287,
 'PRV53895': 1273,
 'PRV52114': 1269,
 'PRV55913': 1267,
 'PRV53750': 1245,
 'PRV52120': 1231,
 'PRV57173': 1225,
 'PRV53871': 1220,
 'PRV53394': 1215,
 'PRV55552': 1206,
 'PRV52104': 1189,
 'PRV52001': 1177,
 'PRV53670': 1173,
 'PRV51005': 1165,
 'PRV52077': 1156,
 'PRV56268': 1113,
 'PRV56559': 1113,
 'PRV56249': 1110,
 'PRV57209': 1108,
 'PRV56006': 1090,
 'PRV52631': 1057,
 'PRV54813': 1056,
 'PRV56270': 1043,
 'PRV53385': 1037,
 'PRV54688': 1032,
 'PRV51509': 1030,
 'PRV51507': 1013,
 'PRV53702': 1010,
 'PRV57333': 1004,
 'PRV52605': 1000,
 'PRV54332': 995,
 'PRV56248': 934,
 'PRV55525': 933,
 'PRV57348': 920,
 'PRV53700': 913,
 'PRV52395': 912,
 'PRV52859': 911,
 'PRV51393': 910,
 'PRV56243': 909,
 'PRV53623': 894,
 'PRV56556': 880,
 'PRV55715': 864,
 'PRV55510': 861,
 'PRV57715': 860,
 'PRV56608': 856,
 'PRV54374': 854,
 'PRV52648': 842,
 'PRV54690': 840,
 'PRV56575': 830,
 'PRV54745': 828,
 'PRV53679': 826,
 'PRV52085': 824,
 'PRV54761': 822,
 'PRV55831': 810,
 'PRV57335': 807,
 'PRV52827': 804,
 'PRV54564': 803,
 'PRV56803': 795,
 'PRV55453': 795,
 'PRV52063': 792,
 'PRV53900': 789,
 'PRV51860': 776,
 'PRV52656': 775,
 'PRV52337': 773,
 'PRV53921': 768,
 'PRV55000': 764,
 'PRV55209': 762,
 'PRV53799': 753,
 'PRV51959': 751,
 'PRV52071': 749,
 'PRV52652': 743,
 'PRV52154': 742,
 'PRV52365': 739,
 'PRV55169': 721,
 'PRV55943': 721,
 'PRV51196': 720,
 'PRV56437': 719,
 'PRV53958': 713,
 'PRV52821': 713,
 'PRV52884': 707,
 'PRV53000': 703,
 'PRV55158': 698,
 'PRV55969': 688,
 'PRV57305': 675,
 'PRV55479': 672,
 'PRV52141': 671,
 'PRV56019': 659,
 'PRV55934': 653,
 'PRV55037': 649,
 'PRV56213': 643,
 'PRV51954': 643,
 'PRV56760': 643,
 'PRV52982': 643,
 'PRV52889': 640,
 'PRV54367': 636,
 'PRV51410': 628,
 'PRV52032': 627,
 'PRV55064': 621,
 'PRV55971': 620,
 'PRV53762': 618,
 'PRV54986': 618,
 'PRV55521': 615,
 'PRV55893': 615,
 'PRV52021': 613,
 'PRV55034': 612,
 'PRV52665': 607,
 'PRV52020': 606,
 'PRV55503': 604,
 'PRV52980': 601,
 'PRV52299': 601,
 'PRV53887': 598,
 'PRV52870': 589,
 'PRV56225': 588,
 'PRV55163': 587,
 'PRV52573': 587,
 'PRV56448': 584,
 'PRV52593': 582,
 'PRV53294': 582,
 'PRV57170': 579,
 'PRV53121': 579,
 'PRV55654': 578,
 'PRV55689': 577,
 'PRV52663': 576,
 'PRV54080': 573,
 'PRV56345': 572,
 'PRV51159': 569,
 'PRV53773': 567,
 'PRV55230': 565,
 'PRV54557': 564,
 'PRV57177': 564,
 'PRV55752': 563,
 'PRV53677': 562,
 'PRV55548': 562,
 'PRV53689': 561,
 'PRV56494': 560,
 'PRV52660': 558,
 'PRV51273': 553,
 'PRV55935': 550,
 'PRV52369': 547,
 'PRV53915': 545,
 'PRV51156': 542,
 'PRV51539': 538,
 'PRV53911': 536,
 'PRV52829': 533,
 'PRV57346': 532,
 'PRV56758': 531,
 'PRV52887': 530,
 'PRV57228': 529,
 'PRV55264': 528,
 'PRV53956': 526,
 'PRV51984': 525,
 'PRV53874': 524,
 'PRV57549': 518,
 'PRV51948': 515,
 'PRV55388': 515,
 'PRV57151': 515,
 'PRV51017': 515,
 'PRV56738': 512,
 'PRV53244': 508,
 'PRV52571': 508,
 'PRV52313': 504,
 'PRV52560': 503,
 'PRV51204': 499,
 'PRV55933': 498,
 'PRV53634': 497,
 'PRV53674': 496,
 'PRV52558': 494,
 'PRV53808': 493,
 'PRV53790': 493,
 'PRV57206': 490,
 'PRV54359': 490,
 'PRV54774': 488,
 'PRV53672': 487,
 'PRV51140': 487,
 'PRV56104': 483,
 'PRV55897': 482,
 'PRV54092': 481,
 'PRV56216': 481,
 'PRV55505': 480,
 'PRV57344': 480,
 'PRV57530': 478,
 'PRV55820': 477,
 'PRV51499': 474,
 'PRV53706': 473,
 'PRV52563': 473,
 'PRV56587': 473,
 'PRV51851': 472,
 'PRV54330': 472,
 'PRV53676': 471,
 'PRV55470': 470,
 'PRV52098': 469,
 'PRV56748': 463,
 'PRV54683': 462,
 'PRV55515': 459,
 'PRV52857': 459,
 'PRV57339': 458,
 'PRV57317': 458,
 'PRV53269': 456,
 'PRV51037': 454,
 'PRV52310': 454,
 'PRV55834': 453,
 'PRV51460': 452,
 'PRV55892': 449,
 'PRV55951': 448,
 'PRV52842': 445,
 'PRV51176': 445,
 'PRV56439': 443,
 'PRV55181': 439,
 'PRV51670': 436,
 'PRV56426': 436,
 'PRV54071': 436,
 'PRV52642': 436,
 'PRV52630': 434,
 'PRV52399': 434,
 'PRV54971': 429,
 'PRV51695': 429,
 'PRV52589': 426,
 'PRV57672': 425,
 'PRV52351': 425,
 'PRV51598': 422,
 'PRV55194': 421,
 'PRV53960': 420,
 'PRV54387': 415,
 'PRV57674': 413,
 'PRV54888': 413,
 'PRV57218': 413,
 'PRV54949': 412,
 'PRV56735': 412,
 'PRV57710': 409,
 'PRV52645': 408,
 'PRV57192': 407,
 'PRV54265': 406,
 'PRV56685': 405,
 'PRV57313': 402,
 'PRV54914': 402,
 'PRV55978': 401,
 'PRV52788': 401,
 'PRV57528': 401,
 'PRV57152': 400,
 'PRV53002': 397,
 'PRV52347': 397,
 'PRV55262': 397,
 'PRV51062': 397,
 'PRV52860': 393,
 'PRV57193': 393,
 'PRV53781': 393,
 'PRV56743': 393,
 'PRV55984': 392,
 'PRV52303': 392,
 'PRV51164': 391,
 'PRV51535': 388,
 'PRV54514': 387,
 'PRV53374': 387,
 'PRV53710': 385,
 'PRV55822': 384,
 'PRV51386': 382,
 'PRV55937': 382,
 'PRV53335': 381,
 'PRV56425': 381,
 'PRV52633': 379,
 'PRV53769': 377,
 'PRV51284': 377,
 'PRV55455': 373,
 'PRV56693': 373,
 'PRV55910': 372,
 'PRV57125': 370,
 'PRV52981': 369,
 'PRV55454': 368,
 'PRV52320': 366,
 'PRV53682': 365,
 'PRV56404': 363,
 'PRV52893': 362,
 'PRV53699': 361,
 'PRV55489': 361,
 'PRV54333': 360,
 'PRV52559': 359,
 'PRV55633': 358,
 'PRV55247': 355,
 'PRV55491': 355,
 'PRV57543': 354,
 'PRV53300': 354,
 'PRV51146': 352,
 'PRV54228': 352,
 'PRV52014': 351,
 'PRV57532': 351,
 'PRV56410': 350,
 'PRV56467': 349,
 'PRV54399': 349,
 'PRV54238': 348,
 'PRV56706': 347,
 'PRV55057': 347,
 'PRV55869': 346,
 'PRV53256': 345,
 'PRV55459': 344,
 'PRV55465': 339,
 'PRV57311': 338,
 'PRV57312': 334,
 'PRV53662': 331,
 'PRV54694': 330,
 'PRV51148': 330,
 'PRV51604': 329,
 'PRV55177': 327,
 'PRV55997': 326,
 'PRV52065': 325,
 'PRV55865': 325,
 'PRV55959': 324,
 'PRV56675': 323,
 'PRV55263': 319,
 'PRV54391': 318,
 'PRV57434': 316,
 'PRV51636': 316,
 'PRV54885': 316,
 'PRV54955': 314,
 'PRV52988': 312,
 'PRV56428': 311,
 'PRV56253': 311,
 'PRV55030': 311,
 'PRV52150': 310,
 'PRV55734': 310,
 'PRV54566': 308,
 'PRV54668': 306,
 'PRV55999': 306,
 'PRV52133': 305,
 'PRV56221': 305,
 'PRV56613': 304,
 'PRV55175': 304,
 'PRV53939': 304,
 'PRV53932': 304,
 'PRV51112': 304,
 'PRV52090': 303,
 'PRV55523': 303,
 'PRV51064': 303,
 'PRV53401': 303,
 'PRV52881': 302,
 'PRV55250': 301,
 'PRV54681': 301,
 'PRV53950': 298,
 'PRV57412': 298,
 'PRV52450': 298,
 'PRV52367': 297,
 'PRV53675': 297,
 'PRV54847': 296,
 'PRV57529': 295,
 'PRV55931': 295,
 'PRV55514': 295,
 'PRV54144': 294,
 'PRV51842': 294,
 'PRV56577': 293,
 'PRV52826': 292,
 'PRV53686': 292,
 'PRV56725': 291,
 'PRV53276': 291,
 'PRV57287': 289,
 'PRV55010': 289,
 'PRV56782': 288,
 'PRV53352': 288,
 'PRV55929': 287,
 'PRV55520': 287,
 'PRV55019': 285,
 'PRV55116': 284,
 'PRV55832': 284,
 'PRV52722': 283,
 'PRV57129': 282,
 'PRV54257': 282,
 'PRV56598': 280,
 'PRV52561': 280,
 'PRV52935': 280,
 'PRV52017': 280,
 'PRV54083': 279,
 'PRV57319': 279,
 'PRV51036': 278,
 'PRV56219': 277,
 'PRV51390': 275,
 'PRV52452': 274,
 'PRV54575': 273,
 'PRV52599': 272,
 'PRV55026': 272,
 'PRV54438': 272,
 'PRV51488': 272,
 'PRV57158': 271,
 'PRV52159': 271,
 'PRV56231': 270,
 'PRV56588': 269,
 'PRV55835': 269,
 'PRV53884': 269,
 'PRV51614': 268,
 'PRV54563': 267,
 'PRV51346': 266,
 'PRV56649': 266,
 'PRV54404': 266,
 'PRV53933': 265,
 'PRV57572': 265,
 'PRV54978': 265,
 'PRV57101': 263,
 'PRV53424': 263,
 'PRV52135': 263,
 'PRV54256': 262,
 'PRV51114': 262,
 'PRV56228': 262,
 'PRV51068': 261,
 'PRV52343': 261,
 'PRV56435': 260,
 'PRV56044': 260,
 'PRV55205': 260,
 'PRV57502': 260,
 'PRV52038': 259,
 'PRV56451': 259,
 'PRV51281': 259,
 'PRV53242': 259,
 'PRV52574': 259,
 'PRV54705': 257,
 'PRV55243': 257,
 'PRV54382': 257,
 'PRV53266': 257,
 'PRV55463': 257,
 'PRV51905': 257,
 'PRV55737': 257,
 'PRV51021': 257,
 'PRV54098': 256,
 'PRV57189': 256,
 'PRV52123': 256,
 'PRV53909': 256,
 'PRV51690': 255,
 'PRV55029': 255,
 'PRV53770': 253,
 'PRV55192': 253,
 'PRV54882': 253,
 'PRV55705': 253,
 'PRV56655': 251,
 'PRV51940': 251,
 'PRV56663': 251,
 'PRV52843': 251,
 'PRV53117': 251,
 'PRV54111': 249,
 'PRV52109': 248,
 'PRV55522': 248,
 'PRV57510': 247,
 'PRV55171': 247,
 'PRV52661': 247,
 'PRV52511': 246,
 'PRV55955': 246,
 'PRV52145': 245,
 'PRV54879': 245,
 'PRV53992': 244,
 'PRV53692': 244,
 'PRV55229': 243,
 'PRV52045': 243,
 'PRV55907': 243,
 'PRV52335': 242,
 'PRV55226': 242,
 'PRV57410': 241,
 'PRV55165': 241,
 'PRV52846': 241,
 'PRV52054': 240,
 'PRV51350': 239,
 'PRV55911': 239,
 'PRV54765': 239,
 'PRV57167': 238,
 'PRV54258': 238,
 'PRV51560': 238,
 'PRV52617': 238,
 'PRV53712': 237,
 'PRV52386': 237,
 'PRV53618': 236,
 'PRV55850': 236,
 'PRV52623': 235,
 'PRV55518': 235,
 'PRV56576': 234,
 'PRV54237': 234,
 'PRV54085': 234,
 'PRV54273': 234,
 'PRV51544': 233,
 'PRV51151': 233,
 'PRV53251': 233,
 'PRV51501': 233,
 'PRV56791': 233,
 'PRV54970': 233,
 'PRV54336': 232,
 'PRV55986': 232,
 'PRV56501': 232,
 'PRV54255': 232,
 'PRV55990': 231,
 'PRV53872': 231,
 'PRV54244': 231,
 'PRV52400': 231,
 'PRV52845': 231,
 'PRV55736': 230,
 'PRV55679': 229,
 'PRV54894': 229,
 'PRV51089': 228,
 'PRV57159': 228,
 'PRV51479': 228,
 'PRV52374': 228,
 'PRV55246': 227,
 'PRV57597': 227,
 'PRV55058': 227,
 'PRV52157': 227,
 'PRV54267': 226,
 'PRV57677': 226,
 'PRV56702': 224,
 'PRV55439': 224,
 'PRV53774': 224,
 'PRV51279': 224,
 'PRV52483': 223,
 'PRV55108': 223,
 'PRV52314': 223,
 'PRV54985': 223,
 'PRV55028': 223,
 'PRV52129': 223,
 'PRV55536': 222,
 'PRV53920': 221,
 'PRV52175': 221,
 'PRV54936': 221,
 'PRV52076': 221,
 'PRV57642': 220,
 'PRV57618': 220,
 'PRV55438': 219,
 'PRV56729': 219,
 'PRV54335': 219,
 'PRV52298': 218,
 'PRV52342': 218,
 'PRV54099': 217,
 'PRV57673': 217,
 'PRV54348': 217,
 'PRV53894': 217,
 'PRV57709': 217,
 'PRV57407': 217,
 'PRV53045': 216,
 'PRV52366': 216,
 'PRV52233': 216,
 'PRV52403': 216,
 'PRV54910': 215,
 'PRV53443': 215,
 'PRV57156': 215,
 'PRV57224': 214,
 'PRV51486': 214,
 'PRV52312': 214,
 'PRV53959': 214,
 'PRV55843': 213,
 'PRV53359': 213,
 'PRV54855': 212,
 'PRV51072': 212,
 'PRV55927': 212,
 'PRV51399': 211,
 'PRV54930': 211,
 'PRV55272': 211,
 'PRV52147': 211,
 'PRV52684': 210,
 'PRV57548': 210,
 'PRV51699': 209,
 'PRV52402': 209,
 'PRV52583': 208,
 'PRV52590': 208,
 'PRV55188': 207,
 'PRV54998': 207,
 'PRV51342': 207,
 'PRV55680': 206,
 'PRV54000': 206,
 'PRV55185': 206,
 'PRV51426': 206,
 'PRV57179': 206,
 'PRV54562': 206,
 'PRV56634': 206,
 'PRV55556': 206,
 'PRV57448': 205,
 'PRV54781': 205,
 'PRV55270': 204,
 'PRV55304': 204,
 'PRV56030': 204,
 'PRV52058': 204,
 'PRV52055': 203,
 'PRV51508': 202,
 'PRV53628': 202,
 'PRV51145': 202,
 'PRV56721': 202,
 'PRV57526': 202,
 'PRV52100': 201,
 'PRV56028': 201,
 'PRV55265': 201,
 'PRV55087': 201,
 'PRV55450': 201,
 'PRV56764': 201,
 'PRV53993': 201,
 'PRV56406': 201,
 'PRV52903': 200,
 'PRV51081': 200,
 'PRV51838': 200,
 'PRV53776': 200,
 'PRV53917': 200,
 'PRV53608': 199,
 'PRV56733': 198,
 'PRV55819': 198,
 'PRV56237': 198,
 'PRV53295': 197,
 'PRV53985': 197,
 'PRV56259': 196,
 'PRV55083': 196,
 'PRV53889': 195,
 'PRV55821': 195,
 'PRV53238': 195,
 'PRV53261': 194,
 'PRV53816': 194,
 'PRV53838': 194,
 'PRV54960': 193,
 'PRV56829': 193,
 'PRV55313': 192,
 'PRV55392': 192,
 'PRV53916': 192,
 'PRV52049': 192,
 'PRV56597': 191,
 'PRV57171': 191,
 'PRV54090': 190,
 'PRV55214': 190,
 'PRV51167': 190,
 'PRV52323': 190,
 'PRV57117': 190,
 'PRV55281': 190,
 'PRV51522': 190,
 'PRV54231': 190,
 'PRV56209': 189,
 'PRV53405': 189,
 'PRV52002': 188,
 'PRV52138': 188,
 'PRV54103': 187,
 'PRV53296': 187,
 'PRV53259': 187,
 'PRV55233': 187,
 'PRV55701': 186,
 'PRV55839': 186,
 'PRV54561': 186,
 'PRV54739': 186,
 'PRV57185': 186,
 'PRV55847': 185,
 'PRV52057': 185,
 'PRV51031': 185,
 'PRV56580': 185,
 'PRV55234': 184,
 'PRV52469': 184,
 'PRV52062': 184,
 'PRV52304': 184,
 'PRV52488': 183,
 'PRV56647': 183,
 'PRV52907': 183,
 'PRV55050': 183,
 'PRV53609': 183,
 'PRV51673': 183,
 'PRV57365': 183,
 'PRV57230': 181,
 'PRV54370': 181,
 'PRV52027': 181,
 'PRV52723': 181,
 'PRV52149': 180,
 'PRV54852': 180,
 'PRV51471': 180,
 'PRV53090': 179,
 'PRV55354': 178,
 'PRV54919': 178,
 'PRV57225': 178,
 'PRV53074': 178,
 'PRV52654': 177,
 'PRV54741': 177,
 'PRV51391': 177,
 'PRV52487': 177,
 'PRV57341': 177,
 'PRV56508': 177,
 'PRV56788': 177,
 'PRV52989': 177,
 'PRV56566': 176,
 'PRV55849': 176,
 'PRV56616': 176,
 'PRV52307': 175,
 'PRV55974': 175,
 'PRV55210': 174,
 'PRV53994': 174,
 'PRV55579': 174,
 'PRV56713': 173,
 'PRV54924': 173,
 'PRV51245': 173,
 'PRV55196': 173,
 'PRV53806': 173,
 'PRV54245': 173,
 'PRV53997': 172,
 'PRV55269': 172,
 'PRV52037': 171,
 'PRV56235': 171,
 'PRV52389': 171,
 'PRV52543': 171,
 'PRV51030': 171,
 'PRV53417': 171,
 'PRV54454': 171,
 'PRV54907': 170,
 'PRV52309': 170,
 'PRV53973': 170,
 'PRV56447': 170,
 'PRV57603': 169,
 'PRV52029': 168,
 'PRV51337': 168,
 'PRV51285': 168,
 'PRV55598': 167,
 'PRV55207': 167,
 'PRV55676': 167,
 'PRV54345': 167,
 'PRV53794': 167,
 'PRV56683': 167,
 'PRV57150': 166,
 'PRV54667': 166,
 'PRV54918': 166,
 'PRV57527': 165,
 'PRV57202': 165,
 'PRV53440': 164,
 'PRV55240': 163,
 'PRV55357': 161,
 'PRV51378': 161,
 'PRV57718': 161,
 'PRV56637': 161,
 'PRV51357': 161,
 'PRV55239': 161,
 'PRV56672': 161,
 'PRV51154': 161,
 'PRV54704': 161,
 'PRV57596': 160,
 'PRV51265': 160,
 'PRV52527': 160,
 'PRV57112': 160,
 'PRV55235': 160,
 'PRV51468': 159,
 'PRV54896': 159,
 'PRV51961': 159,
 'PRV56454': 159,
 'PRV54670': 159,
 'PRV53133': 159,
 'PRV52704': 159,
 'PRV52092': 159,
 'PRV56630': 159,
 'PRV55001': 158,
 'PRV53807': 158,
 'PRV55516': 158,
 'PRV56350': 158,
 'PRV52361': 158,
 'PRV57519': 157,
 'PRV54686': 157,
 'PRV52499': 157,
 'PRV52745': 156,
 'PRV52549': 156,
 'PRV52614': 156,
 'PRV55027': 156,
 'PRV57157': 156,
 'PRV54287': 155,
 'PRV56020': 155,
 'PRV53923': 155,
 'PRV52003': 154,
 'PRV52362': 154,
 'PRV57429': 154,
 'PRV55164': 154,
 'PRV56025': 153,
 'PRV55059': 153,
 'PRV52193': 153,
 'PRV55692': 152,
 'PRV51737': 152,
 'PRV56478': 152,
 'PRV57534': 152,
 'PRV57031': 152,
 'PRV57523': 151,
 'PRV57166': 151,
 'PRV55435': 151,
 'PRV54475': 151,
 'PRV56500': 151,
 'PRV54209': 151,
 'PRV51340': 151,
 'PRV57318': 150,
 'PRV53001': 150,
 'PRV52321': 150,
 'PRV56210': 150,
 'PRV53478': 149,
 'PRV56049': 149,
 'PRV51004': 149,
 'PRV54905': 149,
 'PRV54952': 149,
 'PRV56015': 149,
 'PRV54510': 149,
 'PRV54337': 149,
 'PRV51063': 149,
 'PRV53192': 149,
 'PRV55968': 148,
 'PRV55049': 148,
 'PRV51149': 148,
 'PRV55362': 148,
 'PRV53284': 148,
 'PRV54066': 148,
 'PRV54107': 147,
 'PRV53625': 147,
 'PRV55593': 147,
 'PRV55534': 146,
 'PRV53964': 146,
 'PRV51849': 146,
 'PRV52850': 146,
 'PRV55016': 146,
 'PRV54572': 146,
 'PRV53245': 146,
 'PRV54685': 145,
 'PRV51061': 145,
 'PRV57347': 145,
 'PRV56602': 145,
 'PRV52089': 145,
 'PRV53490': 145,
 'PRV57476': 145,
 'PRV51464': 145,
 'PRV55323': 144,
 'PRV55267': 144,
 'PRV57586': 144,
 'PRV53714': 144,
 'PRV51868': 144,
 'PRV55833': 144,
 'PRV51873': 144,
 'PRV54887': 143,
 'PRV53624': 143,
 'PRV57149': 143,
 'PRV56591': 143,
 'PRV56401': 143,
 'PRV56148': 143,
 'PRV53859': 143,
 'PRV52581': 142,
 'PRV51261': 142,
 'PRV56828': 142,
 'PRV51335': 142,
 'PRV56718': 142,
 'PRV51042': 142,
 'PRV52896': 142,
 'PRV56659': 141,
 'PRV52420': 141,
 'PRV52074': 141,
 'PRV51495': 141,
 'PRV55543': 141,
 'PRV52401': 141,
 'PRV51038': 141,
 'PRV54716': 141,
 'PRV56642': 141,
 'PRV57331': 141,
 'PRV56241': 140,
 'PRV57233': 140,
 'PRV57585': 140,
 'PRV56479': 140,
 'PRV52566': 139,
 'PRV55872': 139,
 'PRV51086': 139,
 'PRV51421': 139,
 'PRV51788': 139,
 'PRV53229': 139,
 'PRV51676': 138,
 'PRV56957': 138,
 'PRV54734': 138,
 'PRV55022': 137,
 'PRV52587': 137,
 'PRV52565': 137,
 'PRV55257': 137,
 'PRV56242': 136,
 'PRV52178': 136,
 'PRV56824': 136,
 'PRV53613': 135,
 'PRV56449': 135,
 'PRV57336': 135,
 'PRV52822': 135,
 'PRV55731': 135,
 'PRV56618': 135,
 'PRV52341': 135,
 'PRV57104': 135,
 'PRV51456': 135,
 'PRV57605': 134,
 'PRV57611': 134,
 'PRV52144': 134,
 'PRV57580': 134,
 'PRV55541': 134,
 'PRV54506': 134,
 'PRV51661': 134,
 'PRV53260': 134,
 'PRV55168': 134,
 'PRV57204': 133,
 'PRV57693': 133,
 'PRV56438': 133,
 'PRV54684': 133,
 'PRV55445': 133,
 'PRV51864': 133,
 'PRV55189': 133,
 'PRV56421': 133,
 'PRV53407': 133,
 'PRV52609': 133,
 'PRV55248': 133,
 'PRV53664': 132,
 'PRV51113': 132,
 'PRV53123': 132,
 'PRV56745': 132,
 'PRV51111': 132,
 'PRV52414': 132,
 'PRV53145': 132,
 'PRV54049': 132,
 'PRV54975': 132,
 'PRV51003': 132,
 'PRV57551': 132,
 'PRV52072': 132,
 'PRV52061': 131,
 'PRV52683': 131,
 'PRV53913': 131,
 'PRV57176': 131,
 'PRV56469': 131,
 'PRV54854': 131,
 'PRV56568': 131,
 'PRV54157': 130,
 'PRV54991': 130,
 'PRV52344': 130,
 'PRV54565': 130,
 'PRV52905': 130,
 'PRV54942': 130,
 'PRV53096': 130,
 'PRV54842': 130,
 'PRV53100': 130,
 'PRV52211': 130,
 'PRV55005': 130,
 'PRV52325': 130,
 'PRV56615': 129,
 'PRV52717': 129,
 'PRV53961': 129,
 'PRV54973': 129,
 'PRV53421': 129,
 'PRV51180': 129,
 'PRV53785': 129,
 'PRV52844': 129,
 'PRV54381': 129,
 'PRV51338': 128,
 'PRV56021': 128,
 'PRV56481': 128,
 'PRV51504': 128,
 'PRV55444': 128,
 'PRV55512': 128,
 'PRV53620': 128,
 'PRV55916': 127,
 'PRV55846': 127,
 'PRV55180': 127,
 'PRV52392': 127,
 'PRV52930': 127,
 'PRV55231': 126,
 'PRV53907': 126,
 'PRV54983': 126,
 'PRV54230': 126,
 'PRV51249': 126,
 'PRV52500': 126,
 'PRV56265': 126,
 'PRV51097': 125,
 'PRV52031': 125,
 'PRV55187': 125,
 ...}

In [77]:
ben_count = final_data['BeneID'].value_counts().to_dict()

In [78]:
ben_count

{'BENE42721': 29,
 'BENE118316': 29,
 'BENE59303': 29,
 'BENE36330': 28,
 'BENE80977': 28,
 'BENE44241': 28,
 'BENE143400': 27,
 'BENE63504': 27,
 'BENE63544': 27,
 'BENE87248': 27,
 'BENE40202': 27,
 'BENE122118': 26,
 'BENE111593': 26,
 'BENE135580': 26,
 'BENE126421': 26,
 'BENE97876': 25,
 'BENE158374': 25,
 'BENE111306': 25,
 'BENE66093': 25,
 'BENE121514': 25,
 'BENE64472': 25,
 'BENE81944': 25,
 'BENE146725': 24,
 'BENE140460': 24,
 'BENE151631': 24,
 'BENE130030': 24,
 'BENE113804': 24,
 'BENE28733': 24,
 'BENE34822': 24,
 'BENE17000': 24,
 'BENE152793': 23,
 'BENE55210': 23,
 'BENE155807': 23,
 'BENE142949': 23,
 'BENE46215': 23,
 'BENE69984': 23,
 'BENE87910': 23,
 'BENE82442': 23,
 'BENE89351': 23,
 'BENE17168': 23,
 'BENE37190': 23,
 'BENE38076': 23,
 'BENE136191': 23,
 'BENE128901': 23,
 'BENE153814': 23,
 'BENE48451': 23,
 'BENE114936': 23,
 'BENE107847': 23,
 'BENE67593': 23,
 'BENE15365': 23,
 'BENE102984': 23,
 'BENE62634': 23,
 'BENE116581': 22,
 'BENE91454': 22,
 'BENE18763': 22,
 'BENE109990': 22,
 'BENE82572': 22,
 'BENE49543': 22,
 'BENE45781': 22,
 'BENE124366': 22,
 'BENE105252': 22,
 'BENE41980': 22,
 'BENE120090': 22,
 'BENE131419': 22,
 'BENE129540': 22,
 'BENE42768': 22,
 'BENE64393': 22,
 'BENE91427': 22,
 'BENE70760': 22,
 'BENE145054': 22,
 'BENE118823': 22,
 'BENE35280': 22,
 'BENE60754': 22,
 'BENE37162': 22,
 'BENE26574': 22,
 'BENE101981': 22,
 'BENE63939': 22,
 'BENE122820': 22,
 'BENE26818': 22,
 'BENE50335': 22,
 'BENE136440': 21,
 'BENE93394': 21,
 'BENE66935': 21,
 'BENE72450': 21,
 'BENE121782': 21,
 'BENE83790': 21,
 'BENE55145': 21,
 'BENE56913': 21,
 'BENE55960': 21,
 'BENE58228': 21,
 'BENE93560': 21,
 'BENE70824': 21,
 'BENE48626': 21,
 'BENE12136': 21,
 'BENE117597': 21,
 'BENE30461': 21,
 'BENE42137': 21,
 'BENE105559': 21,
 'BENE98316': 21,
 'BENE152070': 21,
 'BENE113214': 21,
 'BENE127027': 21,
 'BENE142566': 21,
 'BENE109091': 21,
 'BENE119780': 21,
 'BENE150513': 21,
 'BENE30639': 21,
 'BENE22234': 21,
 'BENE109767': 21,
 'BENE81596': 21,
 'BENE32715': 21,
 'BENE145288': 21,
 'BENE21599': 21,
 'BENE120129': 21,
 'BENE147940': 21,
 'BENE88592': 20,
 'BENE114474': 20,
 'BENE44494': 20,
 'BENE31190': 20,
 'BENE128146': 20,
 'BENE123171': 20,
 'BENE142245': 20,
 'BENE81011': 20,
 'BENE68106': 20,
 'BENE92942': 20,
 'BENE126217': 20,
 'BENE24060': 20,
 'BENE117983': 20,
 'BENE51339': 20,
 'BENE156532': 20,
 'BENE121668': 20,
 'BENE143610': 20,
 'BENE140788': 20,
 'BENE45351': 20,
 'BENE46947': 20,
 'BENE45258': 20,
 'BENE64375': 20,
 'BENE66164': 20,
 'BENE35562': 20,
 'BENE128422': 20,
 'BENE149205': 20,
 'BENE74122': 20,
 'BENE24278': 20,
 'BENE70262': 20,
 'BENE152149': 20,
 'BENE116172': 20,
 'BENE133498': 20,
 'BENE59757': 20,
 'BENE94607': 20,
 'BENE111377': 20,
 'BENE55607': 20,
 'BENE100572': 20,
 'BENE122455': 20,
 'BENE29796': 20,
 'BENE96676': 20,
 'BENE149264': 20,
 'BENE25310': 20,
 'BENE96242': 20,
 'BENE13649': 20,
 'BENE149592': 20,
 'BENE64791': 20,
 'BENE52332': 20,
 'BENE143259': 20,
 'BENE146852': 20,
 'BENE41038': 20,
 'BENE13780': 20,
 'BENE96933': 20,
 'BENE120672': 20,
 'BENE30901': 19,
 'BENE13143': 19,
 'BENE126958': 19,
 'BENE140732': 19,
 'BENE84449': 19,
 'BENE153393': 19,
 'BENE132925': 19,
 'BENE144624': 19,
 'BENE132625': 19,
 'BENE80389': 19,
 'BENE116851': 19,
 'BENE39382': 19,
 'BENE40108': 19,
 'BENE19616': 19,
 'BENE124161': 19,
 'BENE101626': 19,
 'BENE25804': 19,
 'BENE60248': 19,
 'BENE95782': 19,
 'BENE65893': 19,
 'BENE90932': 19,
 'BENE151018': 19,
 'BENE53609': 19,
 'BENE14488': 19,
 'BENE62143': 19,
 'BENE100742': 19,
 'BENE110651': 19,
 'BENE146759': 19,
 'BENE112073': 19,
 'BENE101931': 19,
 'BENE41855': 19,
 'BENE128429': 19,
 'BENE37121': 19,
 'BENE52630': 19,
 'BENE79068': 19,
 'BENE19272': 19,
 'BENE33063': 19,
 'BENE29905': 19,
 'BENE107582': 19,
 'BENE24572': 19,
 'BENE129819': 19,
 'BENE99964': 19,
 'BENE153684': 19,
 'BENE27569': 19,
 'BENE39688': 19,
 'BENE109356': 19,
 'BENE42418': 19,
 'BENE87672': 19,
 'BENE141609': 19,
 'BENE51517': 19,
 'BENE68818': 19,
 'BENE39685': 19,
 'BENE14584': 19,
 'BENE139638': 19,
 'BENE52952': 19,
 'BENE113909': 19,
 'BENE86898': 19,
 'BENE101307': 19,
 'BENE65730': 19,
 'BENE62672': 19,
 'BENE25952': 19,
 'BENE85965': 19,
 'BENE95728': 19,
 'BENE28270': 19,
 'BENE17517': 19,
 'BENE144634': 19,
 'BENE25714': 19,
 'BENE14406': 19,
 'BENE23570': 19,
 'BENE152163': 19,
 'BENE102928': 19,
 'BENE17255': 19,
 'BENE25490': 19,
 'BENE47092': 19,
 'BENE19912': 19,
 'BENE141209': 19,
 'BENE14858': 19,
 'BENE69275': 19,
 'BENE32695': 19,
 'BENE51073': 19,
 'BENE151044': 19,
 'BENE68452': 19,
 'BENE43529': 19,
 'BENE152557': 19,
 'BENE28261': 19,
 'BENE36720': 19,
 'BENE158042': 19,
 'BENE29412': 19,
 'BENE131524': 19,
 'BENE143754': 19,
 'BENE45916': 19,
 'BENE41002': 19,
 'BENE66397': 19,
 'BENE70380': 19,
 'BENE135411': 19,
 'BENE28336': 19,
 'BENE95623': 19,
 'BENE152558': 19,
 'BENE113594': 19,
 'BENE131721': 19,
 'BENE140999': 18,
 'BENE150612': 18,
 'BENE75759': 18,
 'BENE47824': 18,
 'BENE54781': 18,
 'BENE128616': 18,
 'BENE33612': 18,
 'BENE42244': 18,
 'BENE79268': 18,
 'BENE81208': 18,
 'BENE117286': 18,
 'BENE77325': 18,
 'BENE124267': 18,
 'BENE63391': 18,
 'BENE73671': 18,
 'BENE75651': 18,
 'BENE102607': 18,
 'BENE133669': 18,
 'BENE135842': 18,
 'BENE104845': 18,
 'BENE53382': 18,
 'BENE80622': 18,
 'BENE15400': 18,
 'BENE62212': 18,
 'BENE96521': 18,
 'BENE69519': 18,
 'BENE36854': 18,
 'BENE151063': 18,
 'BENE144569': 18,
 'BENE121970': 18,
 'BENE26561': 18,
 'BENE35062': 18,
 'BENE82224': 18,
 'BENE119165': 18,
 'BENE81794': 18,
 'BENE153363': 18,
 'BENE16618': 18,
 'BENE18362': 18,
 'BENE118554': 18,
 'BENE132891': 18,
 'BENE11923': 18,
 'BENE110626': 18,
 'BENE23489': 18,
 'BENE47590': 18,
 'BENE155043': 18,
 'BENE113793': 18,
 'BENE29081': 18,
 'BENE23147': 18,
 'BENE83802': 18,
 'BENE76773': 18,
 'BENE30091': 18,
 'BENE142909': 18,
 'BENE155101': 18,
 'BENE145842': 18,
 'BENE53768': 18,
 'BENE96876': 18,
 'BENE73461': 18,
 'BENE53564': 18,
 'BENE110835': 18,
 'BENE122588': 18,
 'BENE100188': 18,
 'BENE97705': 18,
 'BENE122155': 18,
 'BENE107754': 18,
 'BENE101257': 18,
 'BENE35790': 18,
 'BENE62179': 18,
 'BENE87587': 18,
 'BENE33192': 18,
 'BENE105213': 18,
 'BENE65320': 18,
 'BENE122143': 18,
 'BENE84924': 18,
 'BENE66114': 18,
 'BENE15419': 18,
 'BENE76314': 18,
 'BENE139309': 18,
 'BENE67962': 18,
 'BENE144135': 18,
 'BENE23937': 18,
 'BENE34303': 18,
 'BENE62781': 18,
 'BENE153778': 18,
 'BENE35087': 18,
 'BENE11991': 18,
 'BENE86107': 18,
 'BENE57227': 18,
 'BENE24641': 18,
 'BENE44095': 18,
 'BENE20486': 18,
 'BENE82553': 18,
 'BENE14582': 18,
 'BENE131290': 18,
 'BENE94509': 18,
 'BENE149242': 18,
 'BENE123740': 18,
 'BENE43806': 18,
 'BENE96181': 18,
 'BENE115582': 18,
 'BENE140344': 18,
 'BENE91013': 18,
 'BENE36646': 18,
 'BENE136624': 18,
 'BENE124993': 18,
 'BENE43560': 18,
 'BENE99348': 18,
 'BENE118246': 18,
 'BENE110703': 18,
 'BENE149960': 18,
 'BENE125224': 18,
 'BENE117317': 18,
 'BENE29062': 18,
 'BENE42373': 18,
 'BENE53030': 18,
 'BENE32065': 18,
 'BENE88943': 18,
 'BENE15085': 18,
 'BENE32909': 18,
 'BENE78154': 18,
 'BENE39421': 18,
 'BENE91336': 18,
 'BENE102388': 18,
 'BENE22137': 18,
 'BENE136779': 18,
 'BENE136958': 18,
 'BENE44720': 18,
 'BENE16621': 18,
 'BENE26849': 18,
 'BENE23008': 18,
 'BENE139761': 18,
 'BENE158804': 18,
 'BENE128999': 18,
 'BENE58353': 18,
 'BENE154362': 18,
 'BENE82816': 18,
 'BENE106169': 18,
 'BENE16606': 18,
 'BENE85582': 18,
 'BENE50314': 18,
 'BENE150844': 18,
 'BENE13119': 18,
 'BENE142430': 18,
 'BENE143273': 18,
 'BENE102361': 18,
 'BENE16883': 18,
 'BENE65297': 18,
 'BENE89156': 18,
 'BENE69988': 18,
 'BENE126300': 18,
 'BENE59063': 18,
 'BENE55228': 18,
 'BENE155794': 18,
 'BENE32253': 18,
 'BENE133332': 18,
 'BENE26972': 18,
 'BENE151217': 18,
 'BENE43382': 18,
 'BENE41850': 18,
 'BENE139058': 18,
 'BENE109922': 18,
 'BENE88987': 17,
 'BENE73085': 17,
 'BENE51694': 17,
 'BENE139320': 17,
 'BENE30116': 17,
 'BENE40919': 17,
 'BENE110945': 17,
 'BENE141703': 17,
 'BENE133699': 17,
 'BENE102626': 17,
 'BENE115551': 17,
 'BENE136516': 17,
 'BENE157027': 17,
 'BENE91808': 17,
 'BENE96849': 17,
 'BENE80483': 17,
 'BENE40856': 17,
 'BENE157261': 17,
 'BENE66346': 17,
 'BENE81375': 17,
 'BENE49068': 17,
 'BENE87354': 17,
 'BENE94230': 17,
 'BENE139688': 17,
 'BENE120704': 17,
 'BENE32552': 17,
 'BENE72410': 17,
 'BENE53660': 17,
 'BENE116198': 17,
 'BENE97102': 17,
 'BENE93226': 17,
 'BENE64112': 17,
 'BENE95398': 17,
 'BENE30390': 17,
 'BENE53485': 17,
 'BENE66889': 17,
 'BENE101489': 17,
 'BENE16181': 17,
 'BENE65544': 17,
 'BENE127747': 17,
 'BENE131411': 17,
 'BENE42083': 17,
 'BENE107120': 17,
 'BENE140801': 17,
 'BENE20869': 17,
 'BENE60849': 17,
 'BENE37889': 17,
 'BENE47693': 17,
 'BENE75672': 17,
 'BENE74217': 17,
 'BENE31169': 17,
 'BENE145722': 17,
 'BENE109304': 17,
 'BENE128039': 17,
 'BENE136883': 17,
 'BENE80762': 17,
 'BENE70528': 17,
 'BENE108647': 17,
 'BENE11670': 17,
 'BENE54506': 17,
 'BENE155227': 17,
 'BENE117681': 17,
 'BENE15577': 17,
 'BENE134946': 17,
 'BENE29201': 17,
 'BENE67584': 17,
 'BENE93411': 17,
 'BENE114497': 17,
 'BENE105157': 17,
 'BENE104822': 17,
 'BENE22561': 17,
 'BENE53771': 17,
 'BENE44954': 17,
 'BENE154625': 17,
 'BENE75687': 17,
 'BENE46597': 17,
 'BENE45686': 17,
 'BENE132534': 17,
 'BENE111321': 17,
 'BENE129950': 17,
 'BENE68523': 17,
 'BENE120181': 17,
 'BENE99776': 17,
 'BENE18705': 17,
 'BENE81204': 17,
 'BENE60608': 17,
 'BENE141887': 17,
 'BENE13976': 17,
 'BENE154203': 17,
 'BENE157499': 17,
 'BENE93432': 17,
 'BENE127723': 17,
 'BENE121633': 17,
 'BENE113999': 17,
 'BENE63604': 17,
 'BENE131410': 17,
 'BENE15353': 17,
 'BENE12015': 17,
 'BENE61967': 17,
 'BENE128622': 17,
 'BENE96128': 17,
 'BENE58071': 17,
 'BENE81304': 17,
 'BENE14568': 17,
 'BENE32496': 17,
 'BENE110404': 17,
 'BENE76366': 17,
 'BENE101658': 17,
 'BENE18876': 17,
 'BENE114275': 17,
 'BENE150181': 17,
 'BENE157096': 17,
 'BENE12248': 17,
 'BENE23090': 17,
 'BENE81175': 17,
 'BENE136279': 17,
 'BENE22613': 17,
 'BENE82650': 17,
 'BENE98966': 17,
 'BENE153780': 17,
 'BENE18669': 17,
 'BENE47928': 17,
 'BENE133698': 17,
 'BENE60197': 17,
 'BENE81013': 17,
 'BENE33651': 17,
 'BENE74932': 17,
 'BENE110860': 17,
 'BENE65398': 17,
 'BENE50984': 17,
 'BENE124300': 17,
 'BENE144420': 17,
 'BENE89377': 17,
 'BENE96649': 17,
 'BENE66222': 17,
 'BENE79342': 17,
 'BENE101039': 17,
 'BENE83921': 17,
 'BENE86095': 17,
 'BENE66328': 17,
 'BENE112744': 17,
 'BENE151252': 17,
 'BENE109293': 17,
 'BENE116364': 17,
 'BENE148423': 17,
 'BENE53359': 17,
 'BENE134205': 17,
 'BENE128255': 17,
 'BENE34742': 17,
 'BENE55600': 17,
 'BENE30485': 17,
 'BENE144668': 17,
 'BENE28911': 17,
 'BENE107163': 17,
 'BENE131307': 17,
 'BENE27759': 17,
 'BENE142918': 17,
 'BENE19456': 17,
 'BENE83904': 17,
 'BENE45515': 17,
 'BENE13271': 17,
 'BENE102508': 17,
 'BENE150267': 17,
 'BENE122937': 17,
 'BENE134582': 17,
 'BENE86173': 17,
 'BENE81442': 17,
 'BENE97639': 17,
 'BENE50394': 17,
 'BENE65397': 17,
 'BENE101842': 17,
 'BENE57412': 17,
 'BENE148609': 17,
 'BENE55385': 17,
 'BENE47290': 17,
 'BENE65932': 17,
 'BENE148931': 17,
 'BENE121915': 17,
 'BENE66606': 17,
 'BENE71902': 17,
 'BENE36233': 17,
 'BENE102103': 17,
 'BENE58609': 17,
 'BENE117538': 17,
 'BENE158087': 17,
 'BENE135773': 17,
 'BENE32557': 17,
 'BENE104990': 17,
 'BENE67827': 17,
 'BENE32000': 17,
 'BENE31905': 17,
 'BENE158761': 17,
 'BENE117908': 17,
 'BENE112649': 17,
 'BENE42916': 17,
 'BENE24704': 17,
 'BENE117037': 17,
 'BENE47037': 17,
 'BENE52040': 17,
 'BENE96903': 17,
 'BENE32580': 17,
 'BENE57879': 17,
 'BENE48344': 17,
 'BENE152018': 17,
 'BENE80091': 17,
 'BENE150010': 17,
 'BENE112173': 17,
 'BENE26610': 17,
 'BENE71355': 17,
 'BENE116408': 17,
 'BENE81448': 17,
 'BENE12554': 17,
 'BENE117147': 17,
 'BENE149959': 17,
 'BENE16915': 17,
 'BENE86626': 17,
 'BENE52664': 17,
 'BENE113044': 17,
 'BENE65406': 17,
 'BENE137684': 17,
 'BENE61537': 17,
 'BENE38082': 17,
 'BENE130996': 17,
 'BENE34188': 17,
 'BENE34878': 17,
 'BENE42135': 17,
 'BENE47835': 17,
 'BENE86632': 17,
 'BENE146473': 17,
 'BENE128608': 17,
 'BENE98257': 17,
 'BENE26982': 17,
 'BENE25386': 16,
 'BENE46056': 16,
 'BENE25833': 16,
 'BENE48188': 16,
 'BENE93323': 16,
 'BENE25416': 16,
 'BENE130414': 16,
 'BENE107616': 16,
 'BENE77178': 16,
 'BENE117772': 16,
 'BENE31885': 16,
 'BENE46278': 16,
 'BENE66468': 16,
 'BENE120327': 16,
 'BENE158294': 16,
 'BENE34563': 16,
 'BENE158839': 16,
 'BENE13908': 16,
 'BENE49783': 16,
 'BENE76538': 16,
 'BENE67313': 16,
 'BENE32102': 16,
 'BENE116402': 16,
 'BENE60740': 16,
 'BENE66489': 16,
 'BENE16119': 16,
 'BENE28926': 16,
 'BENE83673': 16,
 'BENE123154': 16,
 'BENE112877': 16,
 'BENE49866': 16,
 'BENE42309': 16,
 'BENE143413': 16,
 'BENE126433': 16,
 'BENE61722': 16,
 'BENE139502': 16,
 'BENE120762': 16,
 'BENE24829': 16,
 'BENE98654': 16,
 'BENE101124': 16,
 'BENE137280': 16,
 'BENE64908': 16,
 'BENE87637': 16,
 'BENE126277': 16,
 'BENE123997': 16,
 'BENE130823': 16,
 'BENE125073': 16,
 'BENE74859': 16,
 'BENE143387': 16,
 'BENE12147': 16,
 'BENE78320': 16,
 'BENE52643': 16,
 'BENE114573': 16,
 'BENE92789': 16,
 'BENE78301': 16,
 'BENE77473': 16,
 'BENE20980': 16,
 'BENE88946': 16,
 'BENE94838': 16,
 'BENE87693': 16,
 'BENE81366': 16,
 'BENE42063': 16,
 'BENE18186': 16,
 'BENE16280': 16,
 'BENE99924': 16,
 'BENE111585': 16,
 'BENE82111': 16,
 'BENE66898': 16,
 'BENE137205': 16,
 'BENE32948': 16,
 'BENE100439': 16,
 'BENE80816': 16,
 'BENE154090': 16,
 'BENE91480': 16,
 'BENE130394': 16,
 'BENE154439': 16,
 'BENE77048': 16,
 'BENE82744': 16,
 'BENE116314': 16,
 'BENE109232': 16,
 'BENE108831': 16,
 'BENE142638': 16,
 'BENE102835': 16,
 'BENE80412': 16,
 'BENE47386': 16,
 'BENE57137': 16,
 'BENE111648': 16,
 'BENE153668': 16,
 'BENE58825': 16,
 'BENE156173': 16,
 'BENE89343': 16,
 'BENE45219': 16,
 'BENE109856': 16,
 'BENE11147': 16,
 'BENE13770': 16,
 'BENE101225': 16,
 'BENE78559': 16,
 'BENE48332': 16,
 'BENE49829': 16,
 'BENE99120': 16,
 'BENE130384': 16,
 'BENE86447': 16,
 'BENE133483': 16,
 'BENE111103': 16,
 'BENE87773': 16,
 'BENE138498': 16,
 'BENE81046': 16,
 'BENE133838': 16,
 'BENE13636': 16,
 'BENE37823': 16,
 'BENE153509': 16,
 'BENE95458': 16,
 'BENE90954': 16,
 'BENE26508': 16,
 'BENE42532': 16,
 'BENE33813': 16,
 'BENE73956': 16,
 'BENE70228': 16,
 'BENE136502': 16,
 'BENE72456': 16,
 'BENE141140': 16,
 'BENE11132': 16,
 'BENE60796': 16,
 'BENE25715': 16,
 'BENE93879': 16,
 'BENE152035': 16,
 'BENE142278': 16,
 'BENE127881': 16,
 'BENE39727': 16,
 'BENE116702': 16,
 'BENE122465': 16,
 'BENE124022': 16,
 'BENE86388': 16,
 'BENE121307': 16,
 'BENE36230': 16,
 'BENE15540': 16,
 'BENE146978': 16,
 'BENE103417': 16,
 'BENE119539': 16,
 'BENE104254': 16,
 'BENE39783': 16,
 'BENE151942': 16,
 'BENE65734': 16,
 'BENE37871': 16,
 'BENE92848': 16,
 'BENE16596': 16,
 'BENE49294': 16,
 'BENE18225': 16,
 'BENE16260': 16,
 'BENE108113': 16,
 'BENE24846': 16,
 'BENE111025': 16,
 'BENE37573': 16,
 'BENE104274': 16,
 'BENE155923': 16,
 'BENE122888': 16,
 'BENE12890': 16,
 'BENE65787': 16,
 'BENE30691': 16,
 'BENE79611': 16,
 'BENE14889': 16,
 'BENE143874': 16,
 'BENE44239': 16,
 'BENE26477': 16,
 'BENE154338': 16,
 'BENE72112': 16,
 'BENE29671': 16,
 'BENE111156': 16,
 'BENE132310': 16,
 'BENE38535': 16,
 'BENE29079': 16,
 'BENE77507': 16,
 'BENE91692': 16,
 'BENE113271': 16,
 'BENE76768': 16,
 'BENE145293': 16,
 'BENE135682': 16,
 'BENE81392': 16,
 'BENE108512': 16,
 'BENE40881': 16,
 'BENE17674': 16,
 'BENE137719': 16,
 'BENE11288': 16,
 'BENE109955': 16,
 'BENE40091': 16,
 'BENE17191': 16,
 'BENE127046': 16,
 'BENE130705': 16,
 'BENE58475': 16,
 'BENE64620': 16,
 'BENE38981': 16,
 'BENE28451': 16,
 'BENE15118': 16,
 'BENE16448': 16,
 'BENE102558': 16,
 'BENE42972': 16,
 'BENE133831': 16,
 'BENE121006': 16,
 'BENE28624': 16,
 'BENE24516': 16,
 'BENE49048': 16,
 'BENE54660': 16,
 'BENE44974': 16,
 'BENE15819': 16,
 'BENE99902': 16,
 'BENE134952': 16,
 'BENE112955': 16,
 'BENE51299': 16,
 'BENE29603': 16,
 'BENE132416': 16,
 'BENE152072': 16,
 'BENE80425': 16,
 'BENE55876': 16,
 'BENE54014': 16,
 'BENE38808': 16,
 'BENE132629': 16,
 'BENE124920': 16,
 'BENE63115': 16,
 'BENE133163': 16,
 'BENE97461': 16,
 'BENE86629': 16,
 'BENE154119': 16,
 'BENE39481': 16,
 'BENE140747': 16,
 'BENE76184': 16,
 'BENE76066': 16,
 'BENE49349': 16,
 'BENE24481': 16,
 'BENE62620': 16,
 'BENE135824': 16,
 'BENE17395': 16,
 'BENE42772': 16,
 'BENE129130': 16,
 'BENE77050': 16,
 'BENE82817': 16,
 'BENE142275': 16,
 'BENE13015': 16,
 'BENE120987': 16,
 'BENE56737': 16,
 'BENE37170': 16,
 'BENE126485': 16,
 'BENE118820': 16,
 'BENE31559': 16,
 'BENE155481': 16,
 'BENE12495': 16,
 'BENE76305': 16,
 'BENE36923': 16,
 'BENE21799': 16,
 'BENE133827': 16,
 'BENE129827': 16,
 'BENE103361': 16,
 'BENE149634': 16,
 'BENE131071': 16,
 'BENE63857': 16,
 'BENE121776': 16,
 'BENE35319': 16,
 'BENE144368': 16,
 'BENE31581': 16,
 'BENE116352': 16,
 'BENE124390': 16,
 'BENE61733': 16,
 'BENE15267': 16,
 'BENE153177': 16,
 'BENE127682': 16,
 'BENE127857': 16,
 'BENE89740': 16,
 'BENE134631': 16,
 'BENE41679': 16,
 'BENE35048': 16,
 'BENE89257': 16,
 'BENE89079': 16,
 'BENE56673': 16,
 'BENE67802': 16,
 'BENE23855': 16,
 'BENE137329': 16,
 'BENE108158': 16,
 'BENE94080': 16,
 'BENE149181': 16,
 'BENE143376': 16,
 'BENE139408': 16,
 'BENE112136': 16,
 'BENE123095': 16,
 'BENE36812': 16,
 'BENE35681': 16,
 'BENE140425': 16,
 'BENE79474': 16,
 'BENE56483': 16,
 'BENE36731': 16,
 'BENE56732': 16,
 'BENE56203': 16,
 'BENE32565': 16,
 'BENE42101': 16,
 'BENE93587': 16,
 'BENE134293': 16,
 'BENE45756': 16,
 'BENE26582': 16,
 'BENE116282': 16,
 'BENE48736': 16,
 'BENE73143': 16,
 'BENE35033': 16,
 'BENE44082': 16,
 'BENE133761': 16,
 'BENE27381': 16,
 'BENE64784': 16,
 'BENE151799': 16,
 'BENE111894': 16,
 'BENE77133': 16,
 'BENE13024': 16,
 'BENE133846': 16,
 'BENE17047': 16,
 'BENE128147': 16,
 'BENE61692': 16,
 'BENE16030': 16,
 'BENE30401': 16,
 'BENE48624': 16,
 'BENE32486': 16,
 'BENE158145': 16,
 'BENE110293': 16,
 'BENE119192': 16,
 'BENE47484': 16,
 'BENE90204': 16,
 'BENE25946': 16,
 'BENE76444': 16,
 'BENE19359': 16,
 'BENE50921': 16,
 'BENE103566': 16,
 'BENE116533': 16,
 'BENE26721': 16,
 'BENE82049': 16,
 'BENE122315': 16,
 'BENE82133': 16,
 'BENE47013': 16,
 'BENE34434': 16,
 'BENE56800': 16,
 'BENE26240': 16,
 'BENE66524': 16,
 'BENE51838': 16,
 'BENE136001': 16,
 'BENE75210': 16,
 'BENE30033': 16,
 ...}

In [79]:
final_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,PHY327147,NaN,NaN,NaN,0.0,NaN,NaN,V7183,53081,78959,4280,E8788,78079,79902,25002,71848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1932-05-01,NaN,1,1,0,39,310,12,12,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,1913-12-01,NaN,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,1922-10-01,NaN,1,1,0,39,600,12,12,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,1930-07-01,NaN,2,1,0,39,280,12,12,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes

In [80]:
final_data['physician_count'] = final_data['AttendingPhysician'].map(physician_count)

In [81]:
final_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes,1.0
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,PHY327147,NaN,NaN,NaN,0.0,NaN,NaN,V7183,53081,78959,4280,E8788,78079,79902,25002,71848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1932-05-01,NaN,1,1,0,39,310,12,12,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes,1.0
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,1913-12-01,NaN,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes,1.0
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,1922-10-01,NaN,1,1,0,39,600,12,12,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes,2.0
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,1930-07-01,NaN,2,1,0,39,280,12,12,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes,3.0

In [83]:
physician_count['PHY390922']

1

In [84]:
final_data[final_data['AttendingPhysician'] == "PHY330576"]

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count
28184,BENE11066,CLM443527,6/30/2009,7/20/2009,PRV53918,60,PHY330576,NaN,PHY359931,NaN,NaN,0.0,NaN,NaN,7210,7197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1936-03-01,NaN,1,1,0,23,620,12,12,1,1,1,2,2,2,2,1,2,2,2,15000,1068,560,660,Yes,2534.0
28185,BENE11066,CLM470441,7/15/2009,7/15/2009,PRV53918,200,PHY330576,NaN,PHY320218,NaN,NaN,0.0,NaN,NaN,78603,7931,7862,28860,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1936-03-01,NaN,1,1,0,23,620,12,12,1,1,1,2,2,2,2,1,2,2,2,15000,1068,560,660,Yes,2534.0
28187,BENE12065,CLM154715,1/24/2009,1/24/2009,PRV53918,50,PHY330576,NaN,NaN,NaN,7823,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1942-09-01,NaN,1,1,Y,23,810,12,12,1,1,1,1,1,1,1,1,1,1,2,16000,3204,340,630,Yes,2534.0
28190,BENE12136,CLM577544,9/13/2009,9/13/2009,PRV53918,2050,PHY330576,NaN,PHY375607,NaN,NaN,0.0,NaN,NaN,29606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925-11-01,NaN,2,1,0,23,620,12,12,1,2,2,2,2,2,1,1,2,2,2,4080,1068,7650,910,Yes,2534.0
28191,BENE12136,CLM601511,9/27/2009,9/27/2009,PRV53918,1300,PHY330576,NaN,PHY320218,NaN,NaN,0.0,NaN,NaN,42789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925-11-01,NaN,2,1,0,23,620,12,12,1,2,2,2,2,2,1,1,2,2,2,4080,1068,7650,910,Yes,2534.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31766,BENE159013,CLM395945,6/3/2009,6/3/2009,PRV53918,60,PHY330576,PHY330576,NaN,NaN,NaN,0.0,NaN,NaN,V5831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1930-08-01,NaN,1,1,0,23,370,12,12,1,1,2,2,2,1,1,1,1,2,2,0,0,4300,1070,Yes,2534.0
31767,BENE159118,CLM174165,2/3/2009,2/3/2009,PRV53918,60,PHY330576,PHY330576,PHY351111,NaN,NaN,0.0,NaN,NaN,61802,78831,2720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1927-11-01,NaN,1,2,0,23,810,12,12,2,2,2,2,2,2,2,2,2,1,2,0,0,160,1100,Yes,2534.0
31768,BENE159159,CLM321770,4/24/2009,4/24/2009,PRV53918,60,PHY330576,NaN,NaN,NaN,NaN,0.0,NaN,NaN,1750,53081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909-03-01,NaN,1,1,0,23,490,12,12,1,1,2,2,2,1,2,2,2,2,2,0,0,180,40,Yes,2534.0
31770,BENE159159,CLM645284,10/23/2009,10/23/2009,PRV53918,20,PHY330576,NaN,PHY336024,NaN,NaN,0.0,NaN,NaN,V7282,71596,4019,4293,79439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909-03-01,NaN,1,1,0,23,490,12,12,1,1,2,2,2,1,2,2,2,2,2,0,0,180,40,Yes,2534.0
31771,BENE159171,CLM284891,4/4/2009,4/4/2009,PRV53918,90,PHY330576,NaN,NaN,NaN,43310,0.0,NaN,NaN,7802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-03-01,NaN,1,1,Y,10,260,12,12,1,2,2,2,2,2,1,1,1,2,2,0,0,810,600,Yes,2534.0

In [85]:
physician_count['PHY330576']

2534

In [87]:
final_data['provider_count'] = final_data['Provider'].map(provider_count)

In [88]:
final_data['ben_count'] = final_data['BeneID'].map(ben_count)

In [89]:
final_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes,1.0,107,3
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,PHY327147,NaN,NaN,NaN,0.0,NaN,NaN,V7183,53081,78959,4280,E8788,78079,79902,25002,71848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1932-05-01,NaN,1,1,0,39,310,12,12,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes,1.0,107,3
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,1913-12-01,NaN,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes,1.0,107,2
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,1922-10-01,NaN,1,1,0,39,600,12,12,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes,2.0,107,4
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,1930-07-01,NaN,2,1,0,39,280,12,12,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes,3.0,107,7

In [90]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes

In [ ]:
train_inpatient['AdmissionDt'][0]

In [96]:
train_inpatient['DischargeDt'][0]

'2009-04-18'

In [91]:
train_inpatient['AdmissionDt'] = pd.to_datetime(train_inpatient['AdmissionDt'])

In [92]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes

In [93]:
train_inpatient['AdmissionDt'][0]

Timestamp('2009-04-12 00:00:00')

In [97]:
train_inpatient['DischargeDt'] = pd.to_datetime(train_inpatient['DischargeDt'])

In [98]:
train_inpatient['AdmissionDt'][0]

Timestamp('2009-04-12 00:00:00')

In [99]:
train_inpatient['numofdaysadmitted'] = train_inpatient['DischargeDt'] - train_inpatient['AdmissionDt']

In [100]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud,numofdaysadmitted
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,6 days
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes,12 days
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes,18 days
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes,4 days
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes,4 days

In [103]:
train_inpatient['numofdaysadmitted'].value_counts()

3 days     6902
2 days     6117
4 days     4994
1 days     4591
5 days     3579
6 days     2719
7 days     2206
8 days     1613
9 days     1151
10 days     917
11 days     726
0 days      605
12 days     582
13 days     518
14 days     462
15 days     387
35 days     337
16 days     306
17 days     286
18 days     212
19 days     174
21 days     147
20 days     146
22 days     121
23 days     103
24 days      80
27 days      77
28 days      72
25 days      68
26 days      68
29 days      42
32 days      40
33 days      38
30 days      36
34 days      28
31 days      24
Name: numofdaysadmitted, dtype: int64

In [108]:
train_inpatient['numofdaysadmitted']

0        6 days
1       12 days
2       18 days
3        4 days
4        4 days
          ...
43787       NaT
43788       NaT
43789       NaT
43790       NaT
43791       NaT
Name: numofdaysadmitted, Length: 43792, dtype: timedelta64[ns]

In [109]:
train_inpatient['numofdaysadmitted'].isnull() #.isna()

0        False
1        False
2        False
3        False
4        False
         ...
43787     True
43788     True
43789     True
43790     True
43791     True
Name: numofdaysadmitted, Length: 43792, dtype: bool

In [110]:
train_inpatient['numofdaysadmitted'].replace({pd.NaT : "0 days"}, inplace = True)

In [112]:
train_inpatient['numofdaysadmitted']

0         6 days 00:00:00
1        12 days 00:00:00
2        18 days 00:00:00
3         4 days 00:00:00
4         4 days 00:00:00
               ...
43787              0 days
43788              0 days
43789              0 days
43790              0 days
43791              0 days
Name: numofdaysadmitted, Length: 43792, dtype: object

In [117]:
train_inpatient['numofdaysadmitted'].astype(str)

0         6 days 00:00:00
1        12 days 00:00:00
2        18 days 00:00:00
3         4 days 00:00:00
4         4 days 00:00:00
               ...
43787              0 days
43788              0 days
43789              0 days
43790              0 days
43791              0 days
Name: numofdaysadmitted, Length: 43792, dtype: object

In [131]:
train_inpatient['numofdaysadmitted'].astype(str).map(lambda x: int(x.split(" ")[0]))

0         6
1        12
2        18
3         4
4         4
         ..
43787     0
43788     0
43789     0
43790     0
43791     0
Name: numofdaysadmitted, Length: 43792, dtype: int64

In [132]:
train_inpatient['numofdaysadmitted'] = train_inpatient['numofdaysadmitted'].astype(str).map(lambda x: int(x.split(" ")[0]))

In [133]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud,numofdaysadmitted
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,6
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes,12
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes,18
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes,4
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes,4

In [134]:
train_inpatient['physician_count'] = train_inpatient['AttendingPhysician'].map(physician_count)

In [135]:
train_inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,PotentialFraud,numofdaysadmitted,physician_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000.0,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,6,1.0
1,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000.0,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,Yes,12,1.0
2,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000.0,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,Yes,18,2.0
3,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000.0,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,Yes,4,3.0
4,BENE24402,CLM32911,2009-01-08,2009-01-12,PRV55912,3000.0,PHY380413,PHY432598,NaN,2009-01-08,1748,1068.0,2009-01-12,593,2330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8543.0,NaN,NaN,NaN,NaN,NaN,Yes,4,5.0

In [136]:
final_data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,ClmAdmitDiagnosisCode,DeductibleAmtPaid,DischargeDt,DiagnosisGroupCode,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,7866,1068.0,2009-04-18,201,1970,4019,5853,7843,2768,71590,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1943-01-01,NaN,1,1,0,39,230,12,12,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes,1.0,107,3
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,PHY327147,NaN,NaN,NaN,0.0,NaN,NaN,V7183,53081,78959,4280,E8788,78079,79902,25002,71848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1932-05-01,NaN,1,1,0,39,310,12,12,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes,1.0,107,3
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,PHY370861,PHY363291,2009-01-20,45340,1068.0,2009-02-01,987,4240,2639,2948,40390,45821,28489,5854,2753,E9305,NaN,7769.0,5849.0,NaN,NaN,NaN,NaN,1913-12-01,NaN,2,1,0,39,230,12,12,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes,1.0,107,2
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,PHY334706,NaN,2009-10-17,V5789,1068.0,2009-11-04,941,V5789,4168,73313,7812,7993,78830,72273,43812,4019,NaN,9338.0,NaN,NaN,NaN,NaN,NaN,1922-10-01,NaN,1,1,0,39,600,12,12,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes,2.0,107,4
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,PHY323689,PHY363291,2009-10-25,71946,1068.0,2009-10-29,506,71535,71960,4019,V1202,4240,2449,2768,NaN,NaN,NaN,8154.0,NaN,NaN,NaN,NaN,NaN,1930-07-01,NaN,2,1,0,39,280,12,12,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes,3.0,107,7

In [139]:
for col in final_data.columns.tolist():
    print("col name", col)
    print(final_data[col].value_counts())

col name BeneID
BENE42721     29
BENE118316    29
BENE59303     29
BENE36330     28
BENE80977     28
              ..
BENE137989     1
BENE14133      1
BENE30070      1
BENE84103      1
BENE33372      1
Name: BeneID, Length: 138556, dtype: int64
col name ClaimID
CLM634921    1
CLM453735    1
CLM276715    1
CLM134856    1
CLM398192    1
            ..
CLM330641    1
CLM77601     1
CLM472808    1
CLM547967    1
CLM667175    1
Name: ClaimID, Length: 558211, dtype: int64
col name ClaimStartDt
3/3/2009      1574
3/21/2009     1567
1/31/2009     1566
4/25/2009     1550
2/16/2009     1549
              ...
2008-11-28       2
2008-12-10       1
2009-12-31       1
2008-12-03       1
2008-12-06       1
Name: ClaimStartDt, Length: 783, dtype: int64
col name ClaimEndDt
3/3/2009      1563
3/21/2009     1561
4/23/2009     1554
5/1/2009      1548
6/20/2009     1542
              ...
2009-11-29      82
2009-10-19      79
2009-11-11      77
2009-12-25      75
12/28/2008       1
Name: ClaimEndDt, Length: 731, dtype: int64
col name Provider
PRV51459    8240
PRV53797    4739
PRV51574    4444
PRV53918    3588
PRV54895    3436
            ...
PRV54304       1
PRV56339       1
PRV52537       1
PRV56286       1
PRV54621       1
Name: Provider, Length: 5410, dtype: int64
col name InscClaimAmtReimbursed
100      52960
10       42463
200      41634
60       40764
30       33920
         ...
8070         1
8300         1
2480         1
17100        1
10050        1
Name: InscClaimAmtReimbursed, Length: 438, dtype: int64
col name AttendingPhysician
PHY330576    2534
PHY350277    1628
PHY412132    1321
PHY423534    1223
PHY314027    1200
             ...
PHY413819       1
PHY365704       1
PHY398100       1
PHY316502       1
PHY344463       1
Name: AttendingPhysician, Length: 82063, dtype: int64
col name OperatingPhysician
PHY330576    424
PHY424897    293
PHY314027    256
PHY423534    250
PHY357120    249
            ...
PHY429554      1
PHY334211      1
PHY377008      1
PHY380236      1
PHY360535      1
Name: OperatingPhysician, Length: 35315, dtype: int64
col name OtherPhysician
PHY412132    1247
PHY341578    1098
PHY338032    1070
PHY337425    1041
PHY347064     806
             ...
PHY352571       1
PHY383505       1
PHY415137       1
PHY377665       1
PHY360535       1
Name: OtherPhysician, Length: 46457, dtype: int64
col name AdmissionDt
2009-02-10    144
2009-01-31    143
2009-02-26    143
2009-01-06    140
2009-02-02    138
             ...
2008-11-27      2
2008-12-10      1
2008-12-03      1
2008-12-06      1
2009-12-31      1
Name: AdmissionDt, Length: 398, dtype: int64
col name ClmAdmitDiagnosisCode
V7612    4074
42731    3634
78605    2992
4019     2732
25000    2368
         ...
4250        1
37023       1
56738       1
3061        1
7013        1
Name: ClmAdmitDiagnosisCode, Length: 4102, dtype: int64
col name DeductibleAmtPaid
0.0       496701
1068.0     39575
100.0       4582
70.0        2420
60.0        2065
40.0        2045
80.0        2024
50.0        1969
20.0        1406
30.0        1336
90.0        1245
10.0        1203
200.0        734
897.0          2
876.0          2
865.0          2
886.0          1
Name: DeductibleAmtPaid, dtype: int64
col name DischargeDt
2009-02-11    153
2009-01-10    147
2009-03-03    143
2009-04-11    141
2009-06-17    138
             ...
2009-11-03     82
2009-12-23     82
2009-10-19     79
2009-11-11     77
2009-12-25     75
Name: DischargeDt, Length: 365, dtype: int64
col name DiagnosisGroupCode
882    179
884    174
166    168
183    165
939    163
      ...
927      1
775      1
934      1
765      1
768      1
Name: DiagnosisGroupCode, Length: 736, dtype: int64
col name ClmDiagnosisCode_1
4019     13886
4011     12512
2724      3606
2720      3210
2722      3028
         ...
64080        1
9523         1
E9506        1
6179         1
74343        1
Name: ClmDiagnosisCode_1, Length: 10371, dtype: int64
col name ClmDiagnosisCode_2
4019     22378
25000    11744
2724     11272
V5861     9716
V5869     9669
         ...
7489         1
36282        1
67454        1
3971         1
64683        1
Name: ClmDiagnosisCode_2, Length: 5326, dtype: int64
col name ClmDiagnosisCode_3
4019     14408
25000     7946
2724      7368
V5869     6069
V5861     4180
         ...
36477        1
43840        1
1338         1
82031        1
62132        1
Name: ClmDiagnosisCode_3, Length: 4790, dtype: int64
col name ClmDiagnosisCode_4
4019     9188
25000    5250
2724     4764
V5869    3367
2449     2523
         ...
6227        1
25083       1
71999       1
V1040       1
30471       1
Name: ClmDiagnosisCode_4, Length: 4392, dtype: int64
col name ClmDiagnosisCode_5
4019     6005
25000    3451
2724     2945
V5869    1921
2449     1647
         ...
7593        1
9080        1
V239        1
85300       1
36254       1
Name: ClmDiagnosisCode_5, Length: 3997, dtype: int64
col name ClmDiagnosisCode_6
4019     4170
25000    2506
2724     2072
42731    1312
53081    1248
         ...
1420        1
29644       1
V6120       1
56941       1
36254       1
Name: ClmDiagnosisCode_6, Length: 3640, dtype: int64
col name ClmDiagnosisCode_7
4019     3014
25000    1822
2724     1536
42731    1026
53081    1002
         ...
7014        1
5644        1
1420        1
V6120       1
V748        1
Name: ClmDiagnosisCode_7, Length: 3415, dtype: int64
col name ClmDiagnosisCode_8
4019     2257
25000    1399
2724     1178
42731     809
4280      795
         ...
V1781       1
41081       1
V4360       1
1368        1
36254       1
Name: ClmDiagnosisCode_8, Length: 3093, dtype: int64
col name ClmDiagnosisCode_9
4019     1581
25000    1100
2724      922
4280      665
42731     652
         ...
1624        1
5963        1
V7286       1
V5332       1
3862        1
Name: ClmDiagnosisCode_9, Length: 2797, dtype: int64
col name ClmDiagnosisCode_10
4019     169
25000    125
2724     100
4280      88
53081     78
        ...
9961       1
9972       1
40211      1
2396       1
30471      1
Name: ClmDiagnosisCode_10, Length: 1160, dtype: int64
col name ClmProcedureCode_1
9904.0    1152
8154.0    1022
66.0       900
3893.0     854
3995.0     809
          ...
5091.0       1
9972.0       1
9978.0       1
9992.0       1
4040.0       1
Name: ClmProcedureCode_1, Length: 1117, dtype: int64
col name ClmProcedureCode_2
4019.0    1736
2724.0     843
5849.0     291
311.0      152
2762.0     143
          ...
5111.0       1
4959.0       1
4871.0       1
4829.0       1
1175.0       1
Name: ClmProcedureCode_2, Length: 300, dtype: int64
col name ClmProcedureCode_3
4019.0    201
2724.0    192
5849.0     42
4439.0     29
9971.0     27
         ...
1509.0      1
400.0       1
1622.0      1
6822.0      1
4532.0      1
Name: ClmProcedureCode_3, Length: 154, dtype: int64
col name ClmProcedureCode_4
4019.0    18
2724.0    16
4439.0     7
4139.0     6
5849.0     6
3572.0     4
2762.0     4
4011.0     3
311.0      3
5185.0     3
496.0      2
4422.0     2
3320.0     2
9974.0     2
2763.0     2
5845.0     2
7804.0     2
42.0       2
7840.0     2
185.0      2
2761.0     1
3343.0     1
2752.0     1
2749.0     1
3844.0     1
3849.0     1
3962.0     1
3963.0     1
9986.0     1
7999.0     1
4104.0     1
4240.0     1
7851.0     1
7824.0     1
7823.0     1
7802.0     1
6822.0     1
412.0      1
1511.0     1
5789.0     1
5771.0     1
5121.0     1
5119.0     1
4660.0     1
1122.0     1
4414.0     1
4263.0     1
4269.0     1
Name: ClmProcedureCode_4, dtype: int64
col name ClmProcedureCode_5
4139.0    3
2724.0    2
5185.0    1
4422.0    1
9982.0    1
9971.0    1
Name: ClmProcedureCode_5, dtype: int64
col name ClmProcedureCode_6
Series([], Name: ClmProcedureCode_6, dtype: int64)
col name DOB
1943-12-01    2072
1939-03-01    2030
1942-10-01    1989
1939-04-01    1984
1938-09-01    1971
              ...
1980-05-01      28
1979-01-01      26
1983-02-01      24
1978-04-01      21
1983-03-01      20
Name: DOB, Length: 900, dtype: int64
col name DOD
2009-12-01    710
2009-10-01    572
2009-11-01    560
2009-09-01    511
2009-08-01    482
2009-07-01    371
2009-06-01    295
2009-05-01    243
2009-04-01    166
2009-03-01    157
2009-02-01     64
Name: DOD, dtype: int64
col name Gender
2    323114
1    235097
Name: Gender, dtype: int64
col name Race

1    471036
2     55640
3     19715
5     11820
Name: Race, dtype: int64
col name RenalDiseaseIndicator
0    448363
Y    109848
Name: RenalDiseaseIndicator, dtype: int64
col name State
5     51350
10    39073
33    35024
45    34022
14    24417
39    24251
23    21343
36    21291
34    18905
11    17003
31    15940
49    14997
44    14418
15    14213
22    13624
26    12911
50    11740
21    11261
42    10491
18    10322
1     10240
52     9792
3      9344
19     7917
24     7726
4      7571
16     7457
6      7200
37     6990
25     6682
7      5617
38     5518
17     4884
51     4644
54     4233
28     4168
20     3833
32     3456
46     3381
13     2765
30     2654
43     2002
27     1995
29     1978
47     1827
12     1706
8      1530
41     1110
53     1098
35      940
2       738
9       619
Name: State, dtype: int64
col name County
200    15957
10     13982
20     12632
470    12278
60     11995
       ...
944        2
742        2
834        1
521        1
804        1
Name: County, Length: 314, dtype: int64
col name NoOfMonths_PartACov
12    554722
0       2971
6        116
8        100
11        81
4         55
7         44
10        34
5         30
3         16
2         16
9         13
1         13
Name: NoOfMonths_PartACov, dtype: int64
col name NoOfMonths_PartBCov
12    553918
0       1979
6        728
10       402
11       313
9        242
8        142
7        139
5        126
3         73
4         60
1         48
2         41
Name: NoOfMonths_PartBCov, dtype: int64
col name ChronicCond_Alzheimer
2    333884
1    224327
Name: ChronicCond_Alzheimer, dtype: int64
col name ChronicCond_Heartfailure
1    329583
2    228628
Name: ChronicCond_Heartfailure, dtype: int64
col name ChronicCond_KidneyDisease
2    328227
1    229984
Name: ChronicCond_KidneyDisease, dtype: int64
col name ChronicCond_Cancer
2    473706
1     84505
Name: ChronicCond_Cancer, dtype: int64
col name ChronicCond_ObstrPulmonary
2    383530
1    174681
Name: ChronicCond_ObstrPulmonary, dtype: int64
col name ChronicCond_Depression
2    315497
1    242714
Name: ChronicCond_Depression, dtype: int64
col name ChronicCond_Diabetes
1    393759
2    164452
Name: ChronicCond_Diabetes, dtype: int64
col name ChronicCond_IschemicHeart
1    423830
2    134381
Name: ChronicCond_IschemicHeart, dtype: int64
col name ChronicCond_Osteoporasis
2    380897
1    177314
Name: ChronicCond_Osteoporasis, dtype: int64
col name ChronicCond_rheumatoidarthritis
2    384512
1    173699
Name: ChronicCond_rheumatoidarthritis, dtype: int64
col name ChronicCond_stroke
2    501430
1     56781
Name: ChronicCond_stroke, dtype: int64
col name IPAnnualReimbursementAmt
0         371676
4000        9909
5000        8822
3000        8301
6000        7506
           ...
23500          1
57510          1
31050          1
2110           1
101120         1
Name: IPAnnualReimbursementAmt, Length: 3004, dtype: int64
col name IPAnnualDeductibleAmt
0        369267
1068     125646
2136      40454
3204      11730
4272       3420
          ...
37204         3
10436         2
14068         2
9408          1
1118          1
Name: IPAnnualDeductibleAmt, Length: 147, dtype: int64
col name OPAnnualReimbursementAmt
 100      5950
 200      5443
 0        4918
 300      4578
 400      4318
          ...
 14510       1
 32710       1
 9020        1
 24870       1
-40          1
Name: OPAnnualReimbursementAmt, Length: 2078, dtype: int64
col name OPAnnualDeductibleAmt
0       20131
20      14295
100     11939
30      11195
10      11175
        ...
2108        2
9130        2
897         2
1197        2
3860        2
Name: OPAnnualDeductibleAmt, Length: 789, dtype: int64
col name PotentialFraud
No     345415
Yes    212796
Name: PotentialFraud, dtype: int64
col name physician_count
1.0      36099
2.0      30344
3.0      23112
4.0      18312
5.0      14975
         ...
174.0      174
172.0      172
171.0      171
169.0      169
165.0      165
Name: physician_count, Length: 362, dtype: int64
col name provider_count
8240    8240
4739    4739
4444    4444
3588    3588
1794    3588
        ...
199      199
179      179
169      169
164      164
163      163
Name: provider_count, Length: 592, dtype: int64
col name ben_count
4     60440
3     58077
5     57840
6     53106
2     50022
7     47642
8     40896
9     34704
1     32874
10    28770
11    22847
12    18888
13    13923
14    11788
15     8280
16     5696
17     3944
18     2880
19     1900
20     1060
21      735
22      616
23      506
24      192
25      175
27      135
26      104
29       87
28       84
Name: ben_count, dtype: int64

In [143]:
final_data['ClmProcedureCode_3'].isnull().sum()

557242

In [145]:
final_data['ClmProcedureCode_3'].value_counts()

4019.0    201
2724.0    192
5849.0     42
4439.0     29
9971.0     27
         ...
1509.0      1
400.0       1
1622.0      1
6822.0      1
4532.0      1
Name: ClmProcedureCode_3, Length: 154, dtype: int64

In [144]:
final_data.shape

(558211, 58)

In [150]:
final_data['ClmProcedureCode_2'].isnull().sum()/len(final_data)*100

99.01650092886022

In [149]:
final_data['ClmProcedureCode_1'].isnull().sum()/len(final_data)*100

95.82415968155411

In [151]:
final_data['ClmProcedureCode_3'].isnull().sum()/len(final_data)*100

99.8264097267879

In [152]:
final_data['ClmProcedureCode_4'].isnull().sum()/len(final_data)*100

99.978861040001

In [153]:
final_data['ClmProcedureCode_5'].isnull().sum()/len(final_data)*100

99.99838770644075

In [154]:
final_data['ClmProcedureCode_6'].isnull().sum()/len(final_data)*100

100.0

In [155]:
final_data['NoOfMonths_PartBCov'].isnull().sum()/len(final_data)*100

0.0

In [157]:
final_data['NoOfMonths_PartBCov'].value_counts(normalize = True)*100

12    99.230936
0      0.354525
6      0.130417
10     0.072016
11     0.056072
9      0.043353
8      0.025438
7      0.024901
5      0.022572
3      0.013077
4      0.010749
1      0.008599
2      0.007345
Name: NoOfMonths_PartBCov, dtype: float64

In [158]:
final_data['NoOfMonths_PartACov'].value_counts(normalize = True)*100

12    99.374968
0      0.532236
6      0.020781
8      0.017914
11     0.014511
4      0.009853
7      0.007882
10     0.006091
5      0.005374
3      0.002866
2      0.002866
9      0.002329
1      0.002329
Name: NoOfMonths_PartACov, dtype: float64

In [ ]:
#If 95% of the data belongs to single value, then there is no importance of that column in prediction

In [212]:
final_data.isnull().sum()/len(final_data1)*100

BeneID                               0.000000
ClaimID                              0.000000
ClaimStartDt                         0.000000
ClaimEndDt                           0.000000
Provider                             0.000000
InscClaimAmtReimbursed               0.000000
AttendingPhysician                   0.270149
OperatingPhysician                  79.497538
OtherPhysician                      64.218548
AdmissionDt                         92.749337
ClmAdmitDiagnosisCode               73.863109
DeductibleAmtPaid                    0.161050
DischargeDt                         92.749337
DiagnosisGroupCode                  92.749337
ClmDiagnosisCode_1                   1.872589
ClmDiagnosisCode_2                  35.041588
ClmDiagnosisCode_3                  56.458221
ClmDiagnosisCode_4                  70.524407
ClmDiagnosisCode_5                  79.949517
ClmDiagnosisCode_6                  84.881702
ClmDiagnosisCode_7                  88.144805
ClmDiagnosisCode_8                  90.425843
ClmDiagnosisCode_9                  92.509105
ClmDiagnosisCode_10                 99.102490
ClmProcedureCode_1                  95.824160
ClmProcedureCode_2                  99.016501
ClmProcedureCode_3                  99.826410
ClmProcedureCode_4                  99.978861
ClmProcedureCode_5                  99.998388
ClmProcedureCode_6                 100.000000
DOB                                  0.000000
DOD                                 99.259957
Gender                               0.000000
Race                                 0.000000
RenalDiseaseIndicator                0.000000
State                                0.000000
County                               0.000000
NoOfMonths_PartACov                  0.000000
NoOfMonths_PartBCov                  0.000000
ChronicCond_Alzheimer                0.000000
ChronicCond_Heartfailure             0.000000
ChronicCond_KidneyDisease            0.000000
ChronicCond_Cancer                   0.000000
ChronicCond_ObstrPulmonary           0.000000
ChronicCond_Depression               0.000000
ChronicCond_Diabetes                 0.000000
ChronicCond_IschemicHeart            0.000000
ChronicCond_Osteoporasis             0.000000
ChronicCond_rheumatoidarthritis      0.000000
ChronicCond_stroke                   0.000000
IPAnnualReimbursementAmt             0.000000
IPAnnualDeductibleAmt                0.000000
OPAnnualReimbursementAmt             0.000000
OPAnnualDeductibleAmt                0.000000
PotentialFraud                       0.000000
physician_count                      0.270149
provider_count                       0.000000
ben_count                            0.000000
dtype: float64

In [213]:
for col in ['AttendingPhysician', 'DeductibleAmtPaid', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'physician_count']:
    print("column: ", col)
    print(final_data[col].value_counts(normalize = True))

column:  AttendingPhysician
PHY330576    0.004552
PHY350277    0.002924
PHY412132    0.002373
PHY423534    0.002197
PHY314027    0.002156
               ...
PHY413819    0.000002
PHY365704    0.000002
PHY398100    0.000002
PHY316502    0.000002
PHY344463    0.000002
Name: AttendingPhysician, Length: 82063, dtype: float64
column:  DeductibleAmtPaid
0.0       0.891244
1068.0    0.071010
100.0     0.008222
70.0      0.004342
60.0      0.003705
40.0      0.003669
80.0      0.003632
50.0      0.003533
20.0      0.002523
30.0      0.002397
90.0      0.002234
10.0      0.002159
200.0     0.001317
897.0     0.000004
876.0     0.000004
865.0     0.000004
886.0     0.000002
Name: DeductibleAmtPaid, dtype: float64
column:  ClmDiagnosisCode_1
4019     0.025351
4011     0.022842
2724     0.006583
2720     0.005860
2722     0.005528
           ...
64080    0.000002
9523     0.000002
E9506    0.000002
6179     0.000002
74343    0.000002
Name: ClmDiagnosisCode_1, Length: 10371, dtype: float64
column:  ClmDiagnosisCode_2
4019     0.061715
25000    0.032388
2724     0.031086
V5861    0.026795
V5869    0.026665
           ...
7489     0.000003
36282    0.000003
67454    0.000003
3971     0.000003
64683    0.000003
Name: ClmDiagnosisCode_2, Length: 5326, dtype: float64
column:  physician_count
1.0      0.064844
2.0      0.054507
3.0      0.041516
4.0      0.032894
5.0      0.026899
           ...
174.0    0.000313
172.0    0.000309
171.0    0.000307
169.0    0.000304
165.0    0.000296
Name: physician_count, Length: 362, dtype: float64

In [268]:
final_data1 = final_data.drop(['NoOfMonths_PartACov','NoOfMonths_PartBCov','ClmProcedureCode_6','ClmProcedureCode_5',
                              'ClmProcedureCode_4','ClmProcedureCode_3','ClmProcedureCode_2', 'ClmProcedureCode_1',
                              'DOD','ClmDiagnosisCode_10','ClmDiagnosisCode_9','ClmDiagnosisCode_8','ClmDiagnosisCode_7',
                               'ClmDiagnosisCode_6','ClmDiagnosisCode_5','ClmDiagnosisCode_4', 'ClmDiagnosisCode_3', 
                               'DiagnosisGroupCode','DischargeDt', 'ClmAdmitDiagnosisCode', 'AdmissionDt',
                               'OtherPhysician', 'OperatingPhysician','DeductibleAmtPaid'], axis = 1)

In [269]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes,1.0,107,3
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes,1.0,107,3
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,2,1,0,39,230,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes,1.0,107,2
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes,2.0,107,4
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,2,1,0,39,280,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes,3.0,107,7

In [270]:
final_data1.describe()

,InscClaimAmtReimbursed,Gender,Race,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,physician_count,provider_count,ben_count
count,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,558211.000000,556703.000000,558211.000000,558211.000000
mean,997.012133,1.578838,1.255011,25.446969,378.588195,1.598132,1.409573,1.587998,1.848615,1.687070,1.565193,1.294605,1.240735,1.682353,1.688829,1.898280,5227.971466,568.756807,2278.225348,649.698745,138.634829,822.488681,6.617216
std,3821.534891,0.493746,0.717437,15.192784,265.215531,0.490276,0.491755,0.492196,0.358424,0.463687,0.495732,0.455866,0.427530,0.465562,0.462973,0.302279,11786.274732,1179.172616,3881.846386,1002.020811,293.669039,1275.484533,4.092040
min,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,-8000.000000,0.000000,-70.000000,0.000000,1.000000,1.000000,1.000000
25%,40.000000,1.000000,1.000000,11.000000,150.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,0.000000,460.000000,120.000000,7.000000,122.000000,3.000000
50%,80.000000,2.000000,1.000000,24.000000,350.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,1.000000,1.000000,2.000000,2.000000,2.000000,0.000000,0.000000,1170.000000,340.000000,33.000000,361.000000,6.000000
75%,300.000000,2.000000,1.000000,38.000000,570.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,2.000000,6000.000000,1068.000000,2590.000000,790.000000,116.000000,1013.000000,9.000000
max,125000.000000,2.000000,5.000000,54.000000,999.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,161470.000000,38272.000000,102960.000000,13840.000000,2534.000000,8240.000000,29.000000

In [271]:
final_data1.shape

(558211, 34)

In [272]:
final_data1.isnull().sum()/len(final_data1)*100

BeneID                              0.000000
ClaimID                             0.000000
ClaimStartDt                        0.000000
ClaimEndDt                          0.000000
Provider                            0.000000
InscClaimAmtReimbursed              0.000000
AttendingPhysician                  0.270149
ClmDiagnosisCode_1                  1.872589
ClmDiagnosisCode_2                 35.041588
DOB                                 0.000000
Gender                              0.000000
Race                                0.000000
RenalDiseaseIndicator               0.000000
State                               0.000000
County                              0.000000
ChronicCond_Alzheimer               0.000000
ChronicCond_Heartfailure            0.000000
ChronicCond_KidneyDisease           0.000000
ChronicCond_Cancer                  0.000000
ChronicCond_ObstrPulmonary          0.000000
ChronicCond_Depression              0.000000
ChronicCond_Diabetes                0.000000
ChronicCond_IschemicHeart           0.000000
ChronicCond_Osteoporasis            0.000000
ChronicCond_rheumatoidarthritis     0.000000
ChronicCond_stroke                  0.000000
IPAnnualReimbursementAmt            0.000000
IPAnnualDeductibleAmt               0.000000
OPAnnualReimbursementAmt            0.000000
OPAnnualDeductibleAmt               0.000000
PotentialFraud                      0.000000
physician_count                     0.270149
provider_count                      0.000000
ben_count                           0.000000
dtype: float64

In [273]:
for c in ['AttendingPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'physician_count']:
    final_data1[c] = final_data1[c].replace({np.nan:0})

In [274]:
# there can be columns which already hv 0 (they're not nan) now replacing nan with 0s 

# hw much % of 0s r there in the columns

# 0s also mean something,

In [275]:
final_data1.isnull().sum()/len(final_data1)*100

BeneID                             0.0
ClaimID                            0.0
ClaimStartDt                       0.0
ClaimEndDt                         0.0
Provider                           0.0
InscClaimAmtReimbursed             0.0
AttendingPhysician                 0.0
ClmDiagnosisCode_1                 0.0
ClmDiagnosisCode_2                 0.0
DOB                                0.0
Gender                             0.0
Race                               0.0
RenalDiseaseIndicator              0.0
State                              0.0
County                             0.0
ChronicCond_Alzheimer              0.0
ChronicCond_Heartfailure           0.0
ChronicCond_KidneyDisease          0.0
ChronicCond_Cancer                 0.0
ChronicCond_ObstrPulmonary         0.0
ChronicCond_Depression             0.0
ChronicCond_Diabetes               0.0
ChronicCond_IschemicHeart          0.0
ChronicCond_Osteoporasis           0.0
ChronicCond_rheumatoidarthritis    0.0
ChronicCond_stroke                 0.0
IPAnnualReimbursementAmt           0.0
IPAnnualDeductibleAmt              0.0
OPAnnualReimbursementAmt           0.0
OPAnnualDeductibleAmt              0.0
PotentialFraud                     0.0
physician_count                    0.0
provider_count                     0.0
ben_count                          0.0
dtype: float64

In [276]:
for col in ['AttendingPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2', 'physician_count']:
    print("column: ", col)
    print(final_data1[col].value_counts(normalize = True))

column:  AttendingPhysician
PHY330576    0.004540
PHY350277    0.002916
0            0.002701
PHY412132    0.002366
PHY423534    0.002191
               ...
PHY405448    0.000002
PHY387203    0.000002
PHY405212    0.000002
PHY322931    0.000002
PHY361836    0.000002
Name: AttendingPhysician, Length: 82064, dtype: float64
column:  ClmDiagnosisCode_1
4019     0.024876
4011     0.022414
0        0.018726
2724     0.006460
2720     0.005751
           ...
3249     0.000002
85303    0.000002
94529    0.000002
80094    0.000002
V0951    0.000002
Name: ClmDiagnosisCode_1, Length: 10372, dtype: float64
column:  ClmDiagnosisCode_2
0        0.350416
4019     0.040089
25000    0.021039
2724     0.020193
V5861    0.017406
           ...
1599     0.000002
82123    0.000002
37842    0.000002
E9041    0.000002
78967    0.000002
Name: ClmDiagnosisCode_2, Length: 5327, dtype: float64
column:  physician_count
1.0      0.064669
2.0      0.054359
3.0      0.041404
4.0      0.032805
5.0      0.026827
           ...
174.0    0.000312
172.0    0.000308
171.0    0.000306
169.0    0.000303
165.0    0.000296
Name: physician_count, Length: 363, dtype: float64

In [277]:
final_data1['physician_count'] = final_data1['physician_count'].replace(0, 1.0)
final_data1['ClmDiagnosisCode_2'] = final_data1['ClmDiagnosisCode_2'].replace(0, '4019') 
final_data1['ClmDiagnosisCode_1'] = final_data1['ClmDiagnosisCode_1'].replace(0, '4019')

In [278]:
final_data1['AttendingPhysician'] = final_data['AttendingPhysician'].replace(0, 'PHY330576')

In [279]:
final_data1.shape

(558211, 34)

In [280]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,2,1,2,2,1,1,1,2,1,1,36000,3204,60,70,Yes,1.0,107,3
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,2,2,2,2,1,2,2,2,24000,2136,450,200,Yes,1.0,107,3
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,2,1,0,39,230,1,1,1,2,1,2,2,1,2,2,2,19000,1068,100,20,Yes,1.0,107,2
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,2,2,2,2,2,2,2,1,1,2,2,17000,1068,1050,540,Yes,2.0,107,4
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,2,1,0,39,280,2,1,2,2,1,2,1,1,1,1,2,27000,2136,450,160,Yes,3.0,107,7

In [281]:
def binary_columns():
    empty = []
    for i in final_data1.columns.tolist():
        if final_data1[i].nunique() <= 2:
            empty.append(i)
    return empty

In [282]:
b_cols = binary_columns()
b_cols

['Gender',
 'RenalDiseaseIndicator',
 'ChronicCond_Alzheimer',
 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease',
 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'PotentialFraud']

In [283]:
for column in b_cols:
    print("col name: ", column)
    print(final_data1[column].value_counts(normalize = True)*100)

col name:  Gender
2    57.883847
1    42.116153
Name: Gender, dtype: float64
col name:  RenalDiseaseIndicator
0    80.32142
Y    19.67858
Name: RenalDiseaseIndicator, dtype: float64
col name:  ChronicCond_Alzheimer
2    59.813225
1    40.186775
Name: ChronicCond_Alzheimer, dtype: float64
col name:  ChronicCond_Heartfailure
1    59.042728
2    40.957272
Name: ChronicCond_Heartfailure, dtype: float64
col name:  ChronicCond_KidneyDisease
2    58.799809
1    41.200191
Name: ChronicCond_KidneyDisease, dtype: float64
col name:  ChronicCond_Cancer
2    84.861459
1    15.138541
Name: ChronicCond_Cancer, dtype: float64
col name:  ChronicCond_ObstrPulmonary
2    68.706994
1    31.293006
Name: ChronicCond_ObstrPulmonary, dtype: float64
col name:  ChronicCond_Depression
2    56.519309
1    43.480691
Name: ChronicCond_Depression, dtype: float64
col name:  ChronicCond_Diabetes
1    70.539456
2    29.460544
Name: ChronicCond_Diabetes, dtype: float64
col name:  ChronicCond_IschemicHeart
1    75.926487
2    24.073513
Name: ChronicCond_IschemicHeart, dtype: float64
col name:  ChronicCond_Osteoporasis
2    68.235309
1    31.764691
Name: ChronicCond_Osteoporasis, dtype: float64
col name:  ChronicCond_rheumatoidarthritis
2    68.882913
1    31.117087
Name: ChronicCond_rheumatoidarthritis, dtype: float64
col name:  ChronicCond_stroke
2    89.82804
1    10.17196
Name: ChronicCond_stroke, dtype: float64
col name:  PotentialFraud
No     61.878931
Yes    38.121069
Name: PotentialFraud, dtype: float64

In [284]:
final_data1['RenalDiseaseIndicator'] = final_data1['RenalDiseaseIndicator'].replace('Y', 1)
final_data1['PotentialFraud'] = final_data1['PotentialFraud'].map({'Yes':1, 'No':0})

In [285]:
few_cols = np.setdiff1d(np.array(b_cols), np.array(['RenalDiseaseIndicator', 'PotentialFraud'])).tolist()
few_cols

['ChronicCond_Alzheimer',
 'ChronicCond_Cancer',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_Heartfailure',
 'ChronicCond_IschemicHeart',
 'ChronicCond_KidneyDisease',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'Gender']

In [286]:
for colum in few_cols:
    final_data1[colum] = final_data1[colum].replace(2,0)

In [287]:
for column in b_cols:
    print("col name: ", column)
    print(final_data1[column].value_counts(normalize = True)*100)

col name:  Gender
0    57.883847
1    42.116153
Name: Gender, dtype: float64
col name:  RenalDiseaseIndicator
0    80.32142
1    19.67858
Name: RenalDiseaseIndicator, dtype: float64
col name:  ChronicCond_Alzheimer
0    59.813225
1    40.186775
Name: ChronicCond_Alzheimer, dtype: float64
col name:  ChronicCond_Heartfailure
1    59.042728
0    40.957272
Name: ChronicCond_Heartfailure, dtype: float64
col name:  ChronicCond_KidneyDisease
0    58.799809
1    41.200191
Name: ChronicCond_KidneyDisease, dtype: float64
col name:  ChronicCond_Cancer
0    84.861459
1    15.138541
Name: ChronicCond_Cancer, dtype: float64
col name:  ChronicCond_ObstrPulmonary
0    68.706994
1    31.293006
Name: ChronicCond_ObstrPulmonary, dtype: float64
col name:  ChronicCond_Depression
0    56.519309
1    43.480691
Name: ChronicCond_Depression, dtype: float64
col name:  ChronicCond_Diabetes
1    70.539456
0    29.460544
Name: ChronicCond_Diabetes, dtype: float64
col name:  ChronicCond_IschemicHeart
1    75.926487
0    24.073513
Name: ChronicCond_IschemicHeart, dtype: float64
col name:  ChronicCond_Osteoporasis
0    68.235309
1    31.764691
Name: ChronicCond_Osteoporasis, dtype: float64
col name:  ChronicCond_rheumatoidarthritis
0    68.882913
1    31.117087
Name: ChronicCond_rheumatoidarthritis, dtype: float64
col name:  ChronicCond_stroke
0    89.82804
1    10.17196
Name: ChronicCond_stroke, dtype: float64
col name:  PotentialFraud
0    61.878931
1    38.121069
Name: PotentialFraud, dtype: float64

In [288]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,0,1,0,0,1,1,1,0,1,1,36000,3204,60,70,1,1.0,107,3
1,BENE16973,CLM565430,9/6/2009,9/6/2009,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,0,0,0,0,1,0,0,0,24000,2136,450,200,1,1.0,107,3
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,0,1,0,39,230,1,1,1,0,1,0,0,1,0,0,0,19000,1068,100,20,1,1.0,107,2
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,0,0,0,0,0,0,0,1,1,0,0,17000,1068,1050,540,1,2.0,107,4
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,0,1,0,39,280,0,1,0,0,1,0,1,1,1,1,0,27000,2136,450,160,1,3.0,107,7

In [289]:
final_data1['ClaimStartDt'] = pd.to_datetime(final_data1['ClaimStartDt'])
final_data1['ClaimEndDt'] = pd.to_datetime(final_data1['ClaimEndDt'])

In [290]:
np.sum(final_data1['ClaimEndDt'] == pd.NaT)

0

In [291]:
final_data1['noofdaysforclaim'] = final_data1['ClaimEndDt'] - final_data1['ClaimStartDt']

In [292]:
np.sum(final_data1['noofdaysforclaim'] == pd.NaT)

0

In [293]:
final_data1['noofdaysforclaim'] = final_data1['noofdaysforclaim'].astype(str).map(lambda x: x.split(" ")[0]).astype('int64')

In [294]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count,noofdaysforclaim
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,0,1,0,0,1,1,1,0,1,1,36000,3204,60,70,1,1.0,107,3,6
1,BENE16973,CLM565430,2009-09-06,2009-09-06,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,0,0,0,0,1,0,0,0,24000,2136,450,200,1,1.0,107,3,0
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,0,1,0,39,230,1,1,1,0,1,0,0,1,0,0,0,19000,1068,100,20,1,1.0,107,2,12
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,0,0,0,0,0,0,0,1,1,0,0,17000,1068,1050,540,1,2.0,107,4,18
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,0,1,0,39,280,0,1,0,0,1,0,1,1,1,1,0,27000,2136,450,160,1,3.0,107,7,4

In [298]:
final_data1['ip_op'] = final_data1['IPAnnualReimbursementAmt'] + final_data1['OPAnnualReimbursementAmt'] - final_data1['IPAnnualDeductibleAmt'] - final_data1['OPAnnualDeductibleAmt']

In [299]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count,noofdaysforclaim,ip_op
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,0,1,0,0,1,1,1,0,1,1,36000,3204,60,70,1,1.0,107,3,6,32786
1,BENE16973,CLM565430,2009-09-06,2009-09-06,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,0,0,0,0,1,0,0,0,24000,2136,450,200,1,1.0,107,3,0,22114
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,0,1,0,39,230,1,1,1,0,1,0,0,1,0,0,0,19000,1068,100,20,1,1.0,107,2,12,18012
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,0,0,0,0,0,0,0,1,1,0,0,17000,1068,1050,540,1,2.0,107,4,18,16442
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,0,1,0,39,280,0,1,0,0,1,0,1,1,1,1,0,27000,2136,450,160,1,3.0,107,7,4,25154

In [302]:
final_data1['total_chronic_diseases'] = final_data1['ChronicCond_Alzheimer'] + final_data1['ChronicCond_Heartfailure'] + final_data1['ChronicCond_KidneyDisease'] + final_data1['ChronicCond_Cancer'] + final_data1['ChronicCond_ObstrPulmonary']+ final_data1['ChronicCond_Depression'] + final_data1['ChronicCond_Diabetes'] + final_data1['ChronicCond_IschemicHeart']+ final_data1['ChronicCond_Osteoporasis'] + final_data1['ChronicCond_rheumatoidarthritis'] + final_data1['ChronicCond_stroke']

In [303]:
final_data1.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,DOB,Gender,Race,RenalDiseaseIndicator,State,County,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt,PotentialFraud,physician_count,provider_count,ben_count,noofdaysforclaim,ip_op,total_chronic_diseases
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,1970,4019,1943-01-01,1,1,0,39,230,1,0,1,0,0,1,1,1,0,1,1,36000,3204,60,70,1,1.0,107,3,6,32786,7
1,BENE16973,CLM565430,2009-09-06,2009-09-06,PRV55912,50,PHY365867,V7183,53081,1932-05-01,1,1,0,39,310,1,1,1,0,0,0,0,1,0,0,0,24000,2136,450,200,1,1.0,107,3,0,22114,4
2,BENE17521,CLM34721,2009-01-20,2009-02-01,PRV55912,19000,PHY349293,4240,2639,1913-12-01,0,1,0,39,230,1,1,1,0,1,0,0,1,0,0,0,19000,1068,100,20,1,1.0,107,2,12,18012,5
3,BENE21718,CLM72336,2009-10-17,2009-11-04,PRV55912,17000,PHY334706,V5789,4168,1922-10-01,1,1,0,39,600,0,0,0,0,0,0,0,1,1,0,0,17000,1068,1050,540,1,2.0,107,4,18,16442,2
4,BENE22934,CLM73394,2009-10-25,2009-10-29,PRV55912,13000,PHY390614,71535,71960,1930-07-01,0,1,0,39,280,0,1,0,0,1,0,1,1,1,1,0,27000,2136,450,160,1,3.0,107,7,4,25154,6

In [304]:
final_data1.shape

(558211, 37)

In [317]:
def startswith(cols):
    a =[ ]
    for i in cols:
        if i.startswith('ChronicCond_'):
            a.append(i)
    return a

In [329]:
l1 = startswith(final_data1.columns.tolist())
dropcols = l1 + ['ClaimStartDt','ClaimEndDt','IPAnnualReimbursementAmt','IPAnnualDeductibleAmt','OPAnnualReimbursementAmt','OPAnnualDeductibleAmt']

['ChronicCond_Alzheimer', 'ChronicCond_Heartfailure', 'ChronicCond_KidneyDisease', 'ChronicCond_Cancer', 'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression', 'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart', 'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis', 'ChronicCond_stroke']

In [330]:
dropcols

['ChronicCond_Alzheimer',
 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease',
 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'ClaimStartDt',
 'ClaimEndDt',
 'IPAnnualReimbursementAmt',
 'IPAnnualDeductibleAmt',
 'OPAnnualReimbursementAmt',
 'OPAnnualDeductibleAmt']

In [ ]:
final_data2 = final_data1.drop([])